# coding: utf-8

"""
    Phrase TMS API

    Welcome to Phrase's TMS API documentation.    Please visit our [help center](https://support.phrase.com/hc/en-us/sections/5709662083612) for more information about the APIs.    If you have any questions, please contact [Support](https://support.phrase.com/hc/requests/new).    Please, include the `User-Agent` header with the name of your application or project. It might be a good idea to include some sort of contact information as well, so that we can get in touch if necessary. Examples of excellent `User-Agent` headers:  > User-Agent: Example mobile app (example@phrase.com) <br/> User-Agent: ACME Inc Java 1.8 Client (http://acmeinc.com/contact)  # noqa: E501

    The version of the OpenAPI document: Latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import phrasetms_client
from phrasetms_client.models.analyse_reference import AnalyseReference  # noqa: E501
from phrasetms_client.rest import ApiException

class TestAnalyseReference(unittest.TestCase):
    """AnalyseReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AnalyseReference
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyseReference`
        """
        model = phrasetms_client.models.analyse_reference.AnalyseReference()  # noqa: E501
        if include_optional :
            return AnalyseReference(
                id = '', 
                uid = '', 
                inner_id = '', 
                type = 'PreAnalyse', 
                name = '', 
                provider = phrasetms_client.models.provider_reference.ProviderReference(
                    type = '', 
                    id = '', 
                    uid = '', ), 
                created_by = phrasetms_client.models.user_reference.UserReference(
                    first_name = '', 
                    last_name = '', 
                    user_name = '', 
                    email = '', 
                    role = 'SYS_ADMIN', 
                    id = '', 
                    uid = '', ), 
                date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                net_rate_scheme = phrasetms_client.models.net_rate_scheme_reference.NetRateSchemeReference(
                    id = '', 
                    uid = '', 
                    name = '', 
                    date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_by = phrasetms_client.models.user_reference.UserReference(
                        first_name = '', 
                        last_name = '', 
                        user_name = '', 
                        email = '', 
                        role = 'SYS_ADMIN', 
                        id = '', 
                        uid = '', ), ), 
                analyse_language_parts = [
                    phrasetms_client.models.analyse_language_part_reference.AnalyseLanguagePartReference(
                        id = '', 
                        source_lang = '', 
                        target_lang = '', 
                        jobs = [
                            phrasetms_client.models.analyse_job_reference.AnalyseJobReference(
                                uid = '', 
                                filename = '', 
                                inner_id = '', )
                            ], )
                    ], 
                outdated = True, 
                import_status = phrasetms_client.models.import_status_dto.ImportStatusDto(
                    status = 'RUNNING', 
                    error_message = '', ), 
                pure_warnings = [
                    ''
                    ]
            )
        else :
            return AnalyseReference(
        )
        """

    def testAnalyseReference(self):
        """Test AnalyseReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
