# coding: utf-8

"""
    Phrase TMS API

    Welcome to Phrase's TMS API documentation.    Please visit our [help center](https://support.phrase.com/hc/en-us/sections/5709662083612) for more information about the APIs.    If you have any questions, please contact [Support](https://support.phrase.com/hc/requests/new).    Please, include the `User-Agent` header with the name of your application or project. It might be a good idea to include some sort of contact information as well, so that we can get in touch if necessary. Examples of excellent `User-Agent` headers:  > User-Agent: Example mobile app (example@phrase.com) <br/> User-Agent: ACME Inc Java 1.8 Client (http://acmeinc.com/contact)  # noqa: E501

    The version of the OpenAPI document: Latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import phrasetms_client
from phrasetms_client.models.mention_dto import MentionDto  # noqa: E501
from phrasetms_client.rest import ApiException

class TestMentionDto(unittest.TestCase):
    """MentionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MentionDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MentionDto`
        """
        model = phrasetms_client.models.mention_dto.MentionDto()  # noqa: E501
        if include_optional :
            return MentionDto(
                mention_type = 'USER', 
                mention_group_type = 'JOB', 
                uid_reference = phrasetms_client.models.uid_reference.UidReference(
                    uid = '', ), 
                user_references = [
                    phrasetms_client.models.mentionable_user_dto.MentionableUserDto(
                        first_name = '', 
                        last_name = '', 
                        user_name = '', 
                        email = '', 
                        role = 'SYS_ADMIN', 
                        id = '', 
                        uid = '', 
                        unavailable = True, 
                        job_roles = [
                            phrasetms_client.models.job_role_dto.JobRoleDto(
                                type = 'PROJECT_OWNER', 
                                workflow_step = phrasetms_client.models.project_workflow_step_dto_v2.ProjectWorkflowStepDtoV2(
                                    id = 56, 
                                    abbreviation = '', 
                                    name = '', 
                                    workflow_level = 56, ), 
                                organization_type = 'VENDOR', )
                            ], )
                    ], 
                mentionable_group = phrasetms_client.models.mentionable_group_dto.MentionableGroupDto(
                    group_type = 'JOB', 
                    group_name = '', 
                    group_reference = phrasetms_client.models.uid_reference.UidReference(
                        uid = '', ), ), 
                tag = ''
            )
        else :
            return MentionDto(
                mention_type = 'USER',
        )
        """

    def testMentionDto(self):
        """Test MentionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
