# coding: utf-8

"""
    Phrase TMS API

    Welcome to Phrase's TMS API documentation.    Please visit our [help center](https://support.phrase.com/hc/en-us/sections/5709662083612) for more information about the APIs.    If you have any questions, please contact [Support](https://support.phrase.com/hc/requests/new).    Please, include the `User-Agent` header with the name of your application or project. It might be a good idea to include some sort of contact information as well, so that we can get in touch if necessary. Examples of excellent `User-Agent` headers:  > User-Agent: Example mobile app (example@phrase.com) <br/> User-Agent: ACME Inc Java 1.8 Client (http://acmeinc.com/contact)  # noqa: E501

    The version of the OpenAPI document: Latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import phrasetms_client
from phrasetms_client.models.match_counts101_dto import MatchCounts101Dto  # noqa: E501
from phrasetms_client.rest import ApiException

class TestMatchCounts101Dto(unittest.TestCase):
    """MatchCounts101Dto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MatchCounts101Dto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatchCounts101Dto`
        """
        model = phrasetms_client.models.match_counts101_dto.MatchCounts101Dto()  # noqa: E501
        if include_optional :
            return MatchCounts101Dto(
                match100 = phrasetms_client.models.counts_dto.CountsDto(
                    segments = 1.337, 
                    words = 1.337, 
                    characters = 1.337, 
                    normalized_pages = 1.337, 
                    percent = 1.337, 
                    editing_time = 1.337, ), 
                match95 = phrasetms_client.models.counts_dto.CountsDto(
                    segments = 1.337, 
                    words = 1.337, 
                    characters = 1.337, 
                    normalized_pages = 1.337, 
                    percent = 1.337, 
                    editing_time = 1.337, ), 
                match85 = phrasetms_client.models.counts_dto.CountsDto(
                    segments = 1.337, 
                    words = 1.337, 
                    characters = 1.337, 
                    normalized_pages = 1.337, 
                    percent = 1.337, 
                    editing_time = 1.337, ), 
                match75 = phrasetms_client.models.counts_dto.CountsDto(
                    segments = 1.337, 
                    words = 1.337, 
                    characters = 1.337, 
                    normalized_pages = 1.337, 
                    percent = 1.337, 
                    editing_time = 1.337, ), 
                match50 = phrasetms_client.models.counts_dto.CountsDto(
                    segments = 1.337, 
                    words = 1.337, 
                    characters = 1.337, 
                    normalized_pages = 1.337, 
                    percent = 1.337, 
                    editing_time = 1.337, ), 
                match0 = phrasetms_client.models.counts_dto.CountsDto(
                    segments = 1.337, 
                    words = 1.337, 
                    characters = 1.337, 
                    normalized_pages = 1.337, 
                    percent = 1.337, 
                    editing_time = 1.337, ), 
                match101 = phrasetms_client.models.counts_dto.CountsDto(
                    segments = 1.337, 
                    words = 1.337, 
                    characters = 1.337, 
                    normalized_pages = 1.337, 
                    percent = 1.337, 
                    editing_time = 1.337, )
            )
        else :
            return MatchCounts101Dto(
        )
        """

    def testMatchCounts101Dto(self):
        """Test MatchCounts101Dto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
