import typing_extensions

from openapi_client.paths import PathValues
from openapi_client.apis.paths.api2_v1_additional_workflow_steps_id import Api2V1AdditionalWorkflowStepsId
from openapi_client.apis.paths.api2_v1_additional_workflow_steps import Api2V1AdditionalWorkflowSteps
from openapi_client.apis.paths.api2_v1_analyses_analyse_uid import Api2V1AnalysesAnalyseUid
from openapi_client.apis.paths.api2_v1_analyses_bulk import Api2V1AnalysesBulk
from openapi_client.apis.paths.api2_v1_analyses_analyse_uid_jobs_job_uid import Api2V1AnalysesAnalyseUidJobsJobUid
from openapi_client.apis.paths.api2_v1_analyses_analyse_uid_download import Api2V1AnalysesAnalyseUidDownload
from openapi_client.apis.paths.api2_v1_analyses_recalculate import Api2V1AnalysesRecalculate
from openapi_client.apis.paths.api2_v1_analyses_analyse_uid_analyse_language_parts_analyse_language_part_id_jobs import Api2V1AnalysesAnalyseUidAnalyseLanguagePartsAnalyseLanguagePartIdJobs
from openapi_client.apis.paths.api2_v1_analyses_by_providers import Api2V1AnalysesByProviders
from openapi_client.apis.paths.api2_v1_analyses_by_languages import Api2V1AnalysesByLanguages
from openapi_client.apis.paths.api2_v1_analyses_analyse_uid_analyse_language_parts_analyse_language_part_id import Api2V1AnalysesAnalyseUidAnalyseLanguagePartsAnalyseLanguagePartId
from openapi_client.apis.paths.api2_v1_async_async_request_id import Api2V1AsyncAsyncRequestId
from openapi_client.apis.paths.api2_v1_async import Api2V1Async
from openapi_client.apis.paths.api2_v1_async_status import Api2V1AsyncStatus
from openapi_client.apis.paths.api2_v1_auth_login import Api2V1AuthLogin
from openapi_client.apis.paths.api2_v1_auth_logout import Api2V1AuthLogout
from openapi_client.apis.paths.api2_v1_auth_login_to_session import Api2V1AuthLoginToSession
from openapi_client.apis.paths.api2_v1_auth_login_other import Api2V1AuthLoginOther
from openapi_client.apis.paths.api2_v1_auth_who_am_i import Api2V1AuthWhoAmI
from openapi_client.apis.paths.api2_v1_auth_login_with_google import Api2V1AuthLoginWithGoogle
from openapi_client.apis.paths.api2_v1_auth_login_with_apple_refresh_token import Api2V1AuthLoginWithAppleRefreshToken
from openapi_client.apis.paths.api2_v1_auth_login_with_apple_code import Api2V1AuthLoginWithAppleCode
from openapi_client.apis.paths.api2_v1_auth_refresh_apple_token import Api2V1AuthRefreshAppleToken
from openapi_client.apis.paths.api2_v1_bilingual_files_convert import Api2V1BilingualFilesConvert
from openapi_client.apis.paths.api2_v1_bilingual_files import Api2V1BilingualFiles
from openapi_client.apis.paths.api2_v1_bilingual_files_compare import Api2V1BilingualFilesCompare
from openapi_client.apis.paths.api2_v1_bilingual_files_preview import Api2V1BilingualFilesPreview
from openapi_client.apis.paths.api2_v1_business_units_business_unit_uid import Api2V1BusinessUnitsBusinessUnitUid
from openapi_client.apis.paths.api2_v1_business_units import Api2V1BusinessUnits
from openapi_client.apis.paths.api2_v1_clients_client_uid import Api2V1ClientsClientUid
from openapi_client.apis.paths.api2_v1_clients import Api2V1Clients
from openapi_client.apis.paths.api2_v1_connectors_connector_id_folders_folder_files_file import Api2V1ConnectorsConnectorIdFoldersFolderFilesFile
from openapi_client.apis.paths.api2_v1_connectors_connector_id import Api2V1ConnectorsConnectorId
from openapi_client.apis.paths.api2_v1_connectors import Api2V1Connectors
from openapi_client.apis.paths.api2_v1_connectors_connector_id_folders_folder import Api2V1ConnectorsConnectorIdFoldersFolder
from openapi_client.apis.paths.api2_v1_connectors_connector_id_folders import Api2V1ConnectorsConnectorIdFolders
from openapi_client.apis.paths.api2_v1_jobs_job_uid_conversations import Api2V1JobsJobUidConversations
from openapi_client.apis.paths.api2_v1_jobs_conversations_find import Api2V1JobsConversationsFind
from openapi_client.apis.paths.api2_v1_cost_centers_cost_center_uid import Api2V1CostCentersCostCenterUid
from openapi_client.apis.paths.api2_v1_cost_centers import Api2V1CostCenters
from openapi_client.apis.paths.api2_v1_custom_fields_field_uid import Api2V1CustomFieldsFieldUid
from openapi_client.apis.paths.api2_v1_custom_fields import Api2V1CustomFields
from openapi_client.apis.paths.api2_v1_custom_fields_field_uid_options import Api2V1CustomFieldsFieldUidOptions
from openapi_client.apis.paths.api2_v1_custom_file_types import Api2V1CustomFileTypes
from openapi_client.apis.paths.api2_v1_custom_file_types_custom_file_type_uid import Api2V1CustomFileTypesCustomFileTypeUid
from openapi_client.apis.paths.api2_v1_net_rate_schemes_net_rate_scheme_uid import Api2V1NetRateSchemesNetRateSchemeUid
from openapi_client.apis.paths.api2_v1_net_rate_schemes import Api2V1NetRateSchemes
from openapi_client.apis.paths.api2_v1_net_rate_schemes_net_rate_scheme_uid_workflow_step_net_schemes_net_rate_scheme_workflow_step_id import Api2V1NetRateSchemesNetRateSchemeUidWorkflowStepNetSchemesNetRateSchemeWorkflowStepId
from openapi_client.apis.paths.api2_v1_net_rate_schemes_net_rate_scheme_uid_workflow_step_net_schemes import Api2V1NetRateSchemesNetRateSchemeUidWorkflowStepNetSchemes
from openapi_client.apis.paths.api2_v1_domains_domain_uid import Api2V1DomainsDomainUid
from openapi_client.apis.paths.api2_v1_domains import Api2V1Domains
from openapi_client.apis.paths.api2_v1_email_templates import Api2V1EmailTemplates
from openapi_client.apis.paths.api2_v1_email_templates_template_uid import Api2V1EmailTemplatesTemplateUid
from openapi_client.apis.paths.api2_v1_projects_project_uid_file_handovers import Api2V1ProjectsProjectUidFileHandovers
from openapi_client.apis.paths.api2_v1_files_file_uid import Api2V1FilesFileUid
from openapi_client.apis.paths.api2_v1_files import Api2V1Files
from openapi_client.apis.paths.api2_v1_glossaries_glossary_uid import Api2V1GlossariesGlossaryUid
from openapi_client.apis.paths.api2_v1_glossaries import Api2V1Glossaries
from openapi_client.apis.paths.api2_v1_glossaries_glossary_uid_activate import Api2V1GlossariesGlossaryUidActivate
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_trans_memories_search_segment import Api2V1ProjectsProjectUidJobsJobUidTransMemoriesSearchSegment
from openapi_client.apis.paths.api2_v1_jobs_job_uid_conversations_lqas_conversation_id_comments_comment_id import Api2V1JobsJobUidConversationsLqasConversationIdCommentsCommentId
from openapi_client.apis.paths.api2_v1_jobs_job_uid_conversations_lqas import Api2V1JobsJobUidConversationsLqas
from openapi_client.apis.paths.api2_v1_jobs_job_uid_conversations_lqas_conversation_id import Api2V1JobsJobUidConversationsLqasConversationId
from openapi_client.apis.paths.api2_v1_languages import Api2V1Languages
from openapi_client.apis.paths.api2_v1_lqa_assessments_reports import Api2V1LqaAssessmentsReports
from openapi_client.apis.paths.api2_v1_lqa_profiles_profile_uid import Api2V1LqaProfilesProfileUid
from openapi_client.apis.paths.api2_v1_lqa_profiles import Api2V1LqaProfiles
from openapi_client.apis.paths.api2_v1_lqa_profiles_profile_uid_duplicate import Api2V1LqaProfilesProfileUidDuplicate
from openapi_client.apis.paths.api2_v1_lqa_profiles_profile_uid_default import Api2V1LqaProfilesProfileUidDefault
from openapi_client.apis.paths.api2_v1_lqa_profiles_authors import Api2V1LqaProfilesAuthors
from openapi_client.apis.paths.api2_v1_machine_translate_settings_mts_uid_status import Api2V1MachineTranslateSettingsMtsUidStatus
from openapi_client.apis.paths.api2_v1_machine_translate_settings import Api2V1MachineTranslateSettings
from openapi_client.apis.paths.api2_v1_machine_translate_settings_mts_uid import Api2V1MachineTranslateSettingsMtsUid
from openapi_client.apis.paths.api2_v1_machine_translate_settings_types import Api2V1MachineTranslateSettingsTypes
from openapi_client.apis.paths.api2_v1_machine_translate_settings_third_party_engines import Api2V1MachineTranslateSettingsThirdPartyEngines
from openapi_client.apis.paths.api2_v1_machine_translations_mt_settings_uid_translate import Api2V1MachineTranslationsMtSettingsUidTranslate
from openapi_client.apis.paths.api2_v1_mappings_tasks_id import Api2V1MappingsTasksId
from openapi_client.apis.paths.api2_v1_import_settings_uid import Api2V1ImportSettingsUid
from openapi_client.apis.paths.api2_v1_import_settings_default import Api2V1ImportSettingsDefault
from openapi_client.apis.paths.api2_v1_import_settings import Api2V1ImportSettings
from openapi_client.apis.paths.api2_v1_jobs_job_uid_conversations_plains_conversation_id import Api2V1JobsJobUidConversationsPlainsConversationId
from openapi_client.apis.paths.api2_v1_jobs_job_uid_conversations_plains import Api2V1JobsJobUidConversationsPlains
from openapi_client.apis.paths.api2_v1_jobs_job_uid_conversations_plains_conversation_id_comments_comment_id import Api2V1JobsJobUidConversationsPlainsConversationIdCommentsCommentId
from openapi_client.apis.paths.api2_v1_projects_project_uid import Api2V1ProjectsProjectUid
from openapi_client.apis.paths.api2_v1_projects_project_uid_workflow_steps import Api2V1ProjectsProjectUidWorkflowSteps
from openapi_client.apis.paths.api2_v1_projects_project_uid_apply_template_template_uid_assign_providers_for_job_parts import Api2V1ProjectsProjectUidApplyTemplateTemplateUidAssignProvidersForJobParts
from openapi_client.apis.paths.api2_v1_projects import Api2V1Projects
from openapi_client.apis.paths.api2_v1_projects_project_uid_target_langs import Api2V1ProjectsProjectUidTargetLangs
from openapi_client.apis.paths.api2_v1_projects_project_uid_assign_vendor import Api2V1ProjectsProjectUidAssignVendor
from openapi_client.apis.paths.api2_v1_projects_project_uid_clone import Api2V1ProjectsProjectUidClone
from openapi_client.apis.paths.api2_v1_projects_project_uid_providers import Api2V1ProjectsProjectUidProviders
from openapi_client.apis.paths.api2_v1_projects_project_uid_set_status import Api2V1ProjectsProjectUidSetStatus
from openapi_client.apis.paths.api2_v1_projects_project_uid_assignable_templates import Api2V1ProjectsProjectUidAssignableTemplates
from openapi_client.apis.paths.api2_v1_projects_project_uid_apply_template_template_uid_assign_providers import Api2V1ProjectsProjectUidApplyTemplateTemplateUidAssignProviders
from openapi_client.apis.paths.api2_v1_projects_project_uid_financial_settings import Api2V1ProjectsProjectUidFinancialSettings
from openapi_client.apis.paths.api2_v1_projects_project_uid_qa_settings_checks import Api2V1ProjectsProjectUidQaSettingsChecks
from openapi_client.apis.paths.api2_v1_projects_project_uid_lqa_settings import Api2V1ProjectsProjectUidLqaSettings
from openapi_client.apis.paths.api2_v1_projects_project_uid_mt_settings import Api2V1ProjectsProjectUidMtSettings
from openapi_client.apis.paths.api2_v1_projects_project_uid_quotes import Api2V1ProjectsProjectUidQuotes
from openapi_client.apis.paths.api2_v1_projects_project_uid_mt_settings_per_language import Api2V1ProjectsProjectUidMtSettingsPerLanguage
from openapi_client.apis.paths.api2_v1_projects_project_uid_analyse_settings import Api2V1ProjectsProjectUidAnalyseSettings
from openapi_client.apis.paths.api2_v1_projects_project_uid_import_settings import Api2V1ProjectsProjectUidImportSettings
from openapi_client.apis.paths.api2_v1_projects_project_uid_file_naming_settings import Api2V1ProjectsProjectUidFileNamingSettings
from openapi_client.apis.paths.api2_v1_projects_project_uid_custom_fields import Api2V1ProjectsProjectUidCustomFields
from openapi_client.apis.paths.api2_v1_projects_project_uid_custom_fields_field_instance_uid import Api2V1ProjectsProjectUidCustomFieldsFieldInstanceUid
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_split import Api2V1ProjectsProjectUidJobsJobUidSplit
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_set_status import Api2V1ProjectsProjectUidJobsJobUidSetStatus
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid import Api2V1ProjectsProjectUidJobsJobUid
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_pseudo_translate import Api2V1ProjectsProjectUidJobsJobUidPseudoTranslate
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_translations import Api2V1ProjectsProjectUidJobsTranslations
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_quality_assurances_ignored_warnings import Api2V1ProjectsProjectUidJobsJobUidQualityAssurancesIgnoredWarnings
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_import_settings import Api2V1ProjectsProjectUidJobsJobUidImportSettings
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_status_changes import Api2V1ProjectsProjectUidJobsJobUidStatusChanges
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_copy_source_to_target import Api2V1ProjectsProjectUidJobsCopySourceToTarget
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_copy_source_to_target import Api2V1ProjectsProjectUidJobsJobUidCopySourceToTarget
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_translation_resources import Api2V1ProjectsProjectUidJobsJobUidTranslationResources
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_segments import Api2V1ProjectsProjectUidJobsJobUidSegments
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_original import Api2V1ProjectsProjectUidJobsJobUidOriginal
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_preview import Api2V1ProjectsProjectUidJobsJobUidPreview
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_target_file_warnings import Api2V1ProjectsProjectUidJobsJobUidTargetFileWarnings
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_preview_url import Api2V1ProjectsProjectUidJobsJobUidPreviewUrl
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs import Api2V1ProjectsProjectUidJobs
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_connector_task import Api2V1ProjectsProjectUidJobsConnectorTask
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_source import Api2V1ProjectsProjectUidJobsSource
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_target import Api2V1ProjectsProjectUidJobsTarget
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_batch import Api2V1ProjectsProjectUidJobsBatch
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_human_translate import Api2V1ProjectsProjectUidJobsHumanTranslate
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_notify_assigned import Api2V1ProjectsProjectUidJobsNotifyAssigned
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_compare import Api2V1ProjectsProjectUidJobsCompare
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_bilingual_file import Api2V1ProjectsProjectUidJobsBilingualFile
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_quality_assurances_ignore_checks import Api2V1ProjectsProjectUidJobsJobUidQualityAssurancesIgnoreChecks
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_workflow_step import Api2V1ProjectsProjectUidJobsJobUidWorkflowStep
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_search import Api2V1ProjectsProjectUidJobsSearch
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_segments_count import Api2V1ProjectsProjectUidJobsSegmentsCount
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_term_bases_create_by_job import Api2V1ProjectsProjectUidJobsJobUidTermBasesCreateByJob
from openapi_client.apis.paths.api2_v1_projects_project_uid_references_creators import Api2V1ProjectsProjectUidReferencesCreators
from openapi_client.apis.paths.api2_v1_projects_project_uid_references import Api2V1ProjectsProjectUidReferences
from openapi_client.apis.paths.api2_v1_projects_project_uid_references_reference_file_id import Api2V1ProjectsProjectUidReferencesReferenceFileId
from openapi_client.apis.paths.api2_v1_projects_project_uid_references_download import Api2V1ProjectsProjectUidReferencesDownload
from openapi_client.apis.paths.api2_v1_project_templates_project_template_uid_trans_memories_relevant import Api2V1ProjectTemplatesProjectTemplateUidTransMemoriesRelevant
from openapi_client.apis.paths.api2_v1_project_templates_project_template_uid_qa_settings import Api2V1ProjectTemplatesProjectTemplateUidQaSettings
from openapi_client.apis.paths.api2_v1_project_templates import Api2V1ProjectTemplates
from openapi_client.apis.paths.api2_v1_project_templates_project_template_uid import Api2V1ProjectTemplatesProjectTemplateUid
from openapi_client.apis.paths.api2_v1_project_templates_project_template_uid_analyse_settings import Api2V1ProjectTemplatesProjectTemplateUidAnalyseSettings
from openapi_client.apis.paths.api2_v1_project_templates_project_template_uid_import_settings import Api2V1ProjectTemplatesProjectTemplateUidImportSettings
from openapi_client.apis.paths.api2_v1_project_templates_project_template_uid_mt_settings import Api2V1ProjectTemplatesProjectTemplateUidMtSettings
from openapi_client.apis.paths.api2_v1_project_templates_project_template_uid_term_bases import Api2V1ProjectTemplatesProjectTemplateUidTermBases
from openapi_client.apis.paths.api2_v1_project_templates_project_template_uid_access_settings import Api2V1ProjectTemplatesProjectTemplateUidAccessSettings
from openapi_client.apis.paths.api2_v1_project_templates_project_template_uid_custom_fields import Api2V1ProjectTemplatesProjectTemplateUidCustomFields
from openapi_client.apis.paths.api2_v1_project_templates_project_template_uid_custom_fields_field_instance_uid import Api2V1ProjectTemplatesProjectTemplateUidCustomFieldsFieldInstanceUid
from openapi_client.apis.paths.api2_v1_projects_project_uid_term_bases import Api2V1ProjectsProjectUidTermBases
from openapi_client.apis.paths.api2_v1_projects_project_uid_term_bases_relevant import Api2V1ProjectsProjectUidTermBasesRelevant
from openapi_client.apis.paths.api2_v1_projects_project_uid_trans_memories_relevant import Api2V1ProjectsProjectUidTransMemoriesRelevant
from openapi_client.apis.paths.api2_v1_projects_project_uid_trans_memories_search_segment_in_project import Api2V1ProjectsProjectUidTransMemoriesSearchSegmentInProject
from openapi_client.apis.paths.api2_v1_quotes_quote_uid import Api2V1QuotesQuoteUid
from openapi_client.apis.paths.api2_v1_quotes_email import Api2V1QuotesEmail
from openapi_client.apis.paths.api2_v1_scim_resource_types import Api2V1ScimResourceTypes
from openapi_client.apis.paths.api2_v1_scim_schemas import Api2V1ScimSchemas
from openapi_client.apis.paths.api2_v1_scim_service_provider_config import Api2V1ScimServiceProviderConfig
from openapi_client.apis.paths.api2_v1_scim_schemas_schema_urn import Api2V1ScimSchemasSchemaUrn
from openapi_client.apis.paths.api2_v1_scim_users_user_id import Api2V1ScimUsersUserId
from openapi_client.apis.paths.api2_v1_scim_users import Api2V1ScimUsers
from openapi_client.apis.paths.api2_v1_segmentation_rules_seg_rule_id import Api2V1SegmentationRulesSegRuleId
from openapi_client.apis.paths.api2_v1_segmentation_rules import Api2V1SegmentationRules
from openapi_client.apis.paths.api2_v1_spell_check_check import Api2V1SpellCheckCheck
from openapi_client.apis.paths.api2_v1_spell_check_check_job_uid import Api2V1SpellCheckCheckJobUid
from openapi_client.apis.paths.api2_v1_spell_check_words import Api2V1SpellCheckWords
from openapi_client.apis.paths.api2_v1_spell_check_suggest import Api2V1SpellCheckSuggest
from openapi_client.apis.paths.api2_v1_sub_domains_sub_domain_uid import Api2V1SubDomainsSubDomainUid
from openapi_client.apis.paths.api2_v1_sub_domains import Api2V1SubDomains
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid import Api2V1TermBasesTermBaseUid
from openapi_client.apis.paths.api2_v1_term_bases import Api2V1TermBases
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid_upload import Api2V1TermBasesTermBaseUidUpload
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid_concepts import Api2V1TermBasesTermBaseUidConcepts
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid_concepts_concept_uid import Api2V1TermBasesTermBaseUidConceptsConceptUid
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid_terms import Api2V1TermBasesTermBaseUidTerms
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid_terms_term_id import Api2V1TermBasesTermBaseUidTermsTermId
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid_concepts_concept_id import Api2V1TermBasesTermBaseUidConceptsConceptId
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid_concepts_concept_id_terms import Api2V1TermBasesTermBaseUidConceptsConceptIdTerms
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid_last_background_task import Api2V1TermBasesTermBaseUidLastBackgroundTask
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid_browse import Api2V1TermBasesTermBaseUidBrowse
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid_search import Api2V1TermBasesTermBaseUidSearch
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid_export import Api2V1TermBasesTermBaseUidExport
from openapi_client.apis.paths.api2_v1_term_bases_term_base_uid_metadata import Api2V1TermBasesTermBaseUidMetadata
from openapi_client.apis.paths.api2_v1_trans_memories_trans_memory_uid_search import Api2V1TransMemoriesTransMemoryUidSearch
from openapi_client.apis.paths.api2_v1_trans_memories import Api2V1TransMemories
from openapi_client.apis.paths.api2_v1_trans_memories_trans_memory_uid import Api2V1TransMemoriesTransMemoryUid
from openapi_client.apis.paths.api2_v1_trans_memories_extract_cleaned import Api2V1TransMemoriesExtractCleaned
from openapi_client.apis.paths.api2_v1_trans_memories_trans_memory_uid_target_languages import Api2V1TransMemoriesTransMemoryUidTargetLanguages
from openapi_client.apis.paths.api2_v1_trans_memories_download_cleaned_async_request_id import Api2V1TransMemoriesDownloadCleanedAsyncRequestId
from openapi_client.apis.paths.api2_v1_trans_memories_trans_memory_uid_segments import Api2V1TransMemoriesTransMemoryUidSegments
from openapi_client.apis.paths.api2_v1_trans_memories_trans_memory_uid_related_projects import Api2V1TransMemoriesTransMemoryUidRelatedProjects
from openapi_client.apis.paths.api2_v1_trans_memories_trans_memory_uid_metadata import Api2V1TransMemoriesTransMemoryUidMetadata
from openapi_client.apis.paths.api2_v1_trans_memories_trans_memory_uid_segments_segment_id import Api2V1TransMemoriesTransMemoryUidSegmentsSegmentId
from openapi_client.apis.paths.api2_v1_trans_memories_trans_memory_uid_segments_segment_id_lang_lang import Api2V1TransMemoriesTransMemoryUidSegmentsSegmentIdLangLang
from openapi_client.apis.paths.api2_v1_trans_memories_trans_memory_uid_last_background_task import Api2V1TransMemoriesTransMemoryUidLastBackgroundTask
from openapi_client.apis.paths.api2_v1_trans_memories_trans_memory_uid_wild_card_search import Api2V1TransMemoriesTransMemoryUidWildCardSearch
from openapi_client.apis.paths.api2_v1_trans_memories_download_export_async_request_id import Api2V1TransMemoriesDownloadExportAsyncRequestId
from openapi_client.apis.paths.api2_v1_trans_memories_trans_memory_uid_export_by_query_async import Api2V1TransMemoriesTransMemoryUidExportByQueryAsync
from openapi_client.apis.paths.api2_v1_projects_project_uid_jobs_job_uid_translations_translate_with_machine_translation import Api2V1ProjectsProjectUidJobsJobUidTranslationsTranslateWithMachineTranslation
from openapi_client.apis.paths.api2_v1_price_lists_price_list_uid import Api2V1PriceListsPriceListUid
from openapi_client.apis.paths.api2_v1_price_lists import Api2V1PriceLists
from openapi_client.apis.paths.api2_v1_price_lists_price_list_uid_price_sets import Api2V1PriceListsPriceListUidPriceSets
from openapi_client.apis.paths.api2_v1_price_lists_price_list_uid_price_sets_source_language_target_language import Api2V1PriceListsPriceListUidPriceSetsSourceLanguageTargetLanguage
from openapi_client.apis.paths.api2_v1_price_lists_price_list_uid_price_sets_minimum_prices import Api2V1PriceListsPriceListUidPriceSetsMinimumPrices
from openapi_client.apis.paths.api2_v1_price_lists_price_list_uid_price_sets_prices import Api2V1PriceListsPriceListUidPriceSetsPrices
from openapi_client.apis.paths.api2_v1_users_user_uid import Api2V1UsersUserUid
from openapi_client.apis.paths.api2_v1_users_user_uid_projects import Api2V1UsersUserUidProjects
from openapi_client.apis.paths.api2_v1_users_last_logins import Api2V1UsersLastLogins
from openapi_client.apis.paths.api2_v1_users_user_uid_jobs import Api2V1UsersUserUidJobs
from openapi_client.apis.paths.api2_v1_users import Api2V1Users
from openapi_client.apis.paths.api2_v1_users_user_uid_update_password import Api2V1UsersUserUidUpdatePassword
from openapi_client.apis.paths.api2_v1_users_user_uid_email_login_information import Api2V1UsersUserUidEmailLoginInformation
from openapi_client.apis.paths.api2_v1_users_user_uid_undelete import Api2V1UsersUserUidUndelete
from openapi_client.apis.paths.api2_v1_users_user_uid_login_statistics import Api2V1UsersUserUidLoginStatistics
from openapi_client.apis.paths.api2_v1_users_user_uid_workflow_steps import Api2V1UsersUserUidWorkflowSteps
from openapi_client.apis.paths.api2_v1_users_user_uid_target_langs import Api2V1UsersUserUidTargetLangs
from openapi_client.apis.paths.api2_v1_vendors_vendor_uid import Api2V1VendorsVendorUid
from openapi_client.apis.paths.api2_v1_vendors import Api2V1Vendors
from openapi_client.apis.paths.api2_v1_webhooks_calls_replay_latest import Api2V1WebhooksCallsReplayLatest
from openapi_client.apis.paths.api2_v1_webhooks_calls import Api2V1WebhooksCalls
from openapi_client.apis.paths.api2_v1_webhooks_calls_replay import Api2V1WebhooksCallsReplay
from openapi_client.apis.paths.api2_v1_workflow_steps import Api2V1WorkflowSteps
from openapi_client.apis.paths.api2_v1_workflow_steps_workflow_step_uid import Api2V1WorkflowStepsWorkflowStepUid
from openapi_client.apis.paths.api2_v2_analyses_analyse_uid import Api2V2AnalysesAnalyseUid
from openapi_client.apis.paths.api2_v2_analyses import Api2V2Analyses
from openapi_client.apis.paths.api2_v2_analyses_bulk import Api2V2AnalysesBulk
from openapi_client.apis.paths.api2_v2_connectors_connector_id_folders_folder_files_file import Api2V2ConnectorsConnectorIdFoldersFolderFilesFile
from openapi_client.apis.paths.api2_v2_connectors_connector_id_folders_folder_files_file_name_upload import Api2V2ConnectorsConnectorIdFoldersFolderFilesFileNameUpload
from openapi_client.apis.paths.api2_v2_connectors_connector_id_folders_folder_files_file_tasks_task_id import Api2V2ConnectorsConnectorIdFoldersFolderFilesFileTasksTaskId
from openapi_client.apis.paths.api2_v2_jobs_workflow_changes import Api2V2JobsWorkflowChanges
from openapi_client.apis.paths.api2_v2_jobs_job_uid_conversations_lqas import Api2V2JobsJobUidConversationsLqas
from openapi_client.apis.paths.api2_v2_jobs_job_uid_conversations_lqas_conversation_id import Api2V2JobsJobUidConversationsLqasConversationId
from openapi_client.apis.paths.api2_v2_jobs_job_uid_conversations_lqas_conversation_id_comments import Api2V2JobsJobUidConversationsLqasConversationIdComments
from openapi_client.apis.paths.api2_v2_jobs_job_uid_conversations_lqas_conversation_id_comments_comment_id import Api2V2JobsJobUidConversationsLqasConversationIdCommentsCommentId
from openapi_client.apis.paths.api2_v2_projects_project_uid_providers_suggest import Api2V2ProjectsProjectUidProvidersSuggest
from openapi_client.apis.paths.api2_v2_projects_apply_template_async_template_uid import Api2V2ProjectsApplyTemplateAsyncTemplateUid
from openapi_client.apis.paths.api2_v2_projects_project_uid_access_settings import Api2V2ProjectsProjectUidAccessSettings
from openapi_client.apis.paths.api2_v2_projects_project_uid_workflow_steps import Api2V2ProjectsProjectUidWorkflowSteps
from openapi_client.apis.paths.api2_v2_projects_project_uid import Api2V2ProjectsProjectUid
from openapi_client.apis.paths.api2_v2_projects_project_uid_qa_settings import Api2V2ProjectsProjectUidQaSettings
from openapi_client.apis.paths.api2_v2_projects_apply_template_template_uid import Api2V2ProjectsApplyTemplateTemplateUid
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs import Api2V2ProjectsProjectUidJobs
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs_job_uid_quality_assurances_settings import Api2V2ProjectsProjectUidJobsJobUidQualityAssurancesSettings
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs_quality_assurances_settings import Api2V2ProjectsProjectUidJobsQualityAssurancesSettings
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs_web_editor import Api2V2ProjectsProjectUidJobsWebEditor
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs_pseudo_translate import Api2V2ProjectsProjectUidJobsPseudoTranslate
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs_pre_translate import Api2V2ProjectsProjectUidJobsPreTranslate
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs_translations import Api2V2ProjectsProjectUidJobsTranslations
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs_job_uid_providers_suggest import Api2V2ProjectsProjectUidJobsJobUidProvidersSuggest
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs_job_uid_target_file import Api2V2ProjectsProjectUidJobsJobUidTargetFile
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs_job_uid_download_target_file_async_request_id import Api2V2ProjectsProjectUidJobsJobUidDownloadTargetFileAsyncRequestId
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs_quality_assurances_ignored_warnings import Api2V2ProjectsProjectUidJobsQualityAssurancesIgnoredWarnings
from openapi_client.apis.paths.api2_v2_project_templates_project_template_uid_trans_memories import Api2V2ProjectTemplatesProjectTemplateUidTransMemories
from openapi_client.apis.paths.api2_v2_quotes import Api2V2Quotes
from openapi_client.apis.paths.api2_v2_trans_memories_trans_memory_uid_export import Api2V2TransMemoriesTransMemoryUidExport
from openapi_client.apis.paths.api2_v2_trans_memories_trans_memory_uid_segments import Api2V2TransMemoriesTransMemoryUidSegments
from openapi_client.apis.paths.api2_v2_trans_memories_trans_memory_uid_import import Api2V2TransMemoriesTransMemoryUidImport
from openapi_client.apis.paths.api2_v2_webhooks_web_hook_uid import Api2V2WebhooksWebHookUid
from openapi_client.apis.paths.api2_v2_webhooks import Api2V2Webhooks
from openapi_client.apis.paths.api2_v2_webhooks_previews import Api2V2WebhooksPreviews
from openapi_client.apis.paths.api2_v2_webhooks_webhook_uid_test import Api2V2WebhooksWebhookUidTest
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs_job_uid_term_bases_search_by_job import Api2V2ProjectsProjectUidJobsJobUidTermBasesSearchByJob
from openapi_client.apis.paths.api2_v2_projects_project_uid_jobs_job_uid_term_bases_search_in_text_by_job import Api2V2ProjectsProjectUidJobsJobUidTermBasesSearchInTextByJob
from openapi_client.apis.paths.api2_v3_analyses_analyse_uid import Api2V3AnalysesAnalyseUid
from openapi_client.apis.paths.api2_v3_auth_login import Api2V3AuthLogin
from openapi_client.apis.paths.api2_v3_auth_login_to_session import Api2V3AuthLoginToSession
from openapi_client.apis.paths.api2_v3_auth_login_other import Api2V3AuthLoginOther
from openapi_client.apis.paths.api2_v3_jobs import Api2V3Jobs
from openapi_client.apis.paths.api2_v3_projects_project_uid_jobs_job_uid_trans_memories_search import Api2V3ProjectsProjectUidJobsJobUidTransMemoriesSearch
from openapi_client.apis.paths.api2_v3_projects_project_uid_jobs_job_uid_trans_memories_wild_card_search import Api2V3ProjectsProjectUidJobsJobUidTransMemoriesWildCardSearch
from openapi_client.apis.paths.api2_v3_jobs_job_uid_conversations_plains_conversation_id_comments import Api2V3JobsJobUidConversationsPlainsConversationIdComments
from openapi_client.apis.paths.api2_v3_jobs_job_uid_conversations_plains import Api2V3JobsJobUidConversationsPlains
from openapi_client.apis.paths.api2_v3_jobs_job_uid_conversations_plains_conversation_id_comments_comment_id import Api2V3JobsJobUidConversationsPlainsConversationIdCommentsCommentId
from openapi_client.apis.paths.api2_v3_projects_project_uid_pre_translate_settings import Api2V3ProjectsProjectUidPreTranslateSettings
from openapi_client.apis.paths.api2_v3_projects_project_uid_analyses import Api2V3ProjectsProjectUidAnalyses
from openapi_client.apis.paths.api2_v3_projects import Api2V3Projects
from openapi_client.apis.paths.api2_v3_projects_project_uid_jobs_export import Api2V3ProjectsProjectUidJobsExport
from openapi_client.apis.paths.api2_v3_projects_project_uid_jobs_job_uid_quality_assurances_run import Api2V3ProjectsProjectUidJobsJobUidQualityAssurancesRun
from openapi_client.apis.paths.api2_v3_projects_project_uid_jobs_quality_assurances_run import Api2V3ProjectsProjectUidJobsQualityAssurancesRun
from openapi_client.apis.paths.api2_v3_projects_project_uid_jobs_quality_assurances_segments_run import Api2V3ProjectsProjectUidJobsQualityAssurancesSegmentsRun
from openapi_client.apis.paths.api2_v3_projects_project_uid_jobs_job_uid_analyses import Api2V3ProjectsProjectUidJobsJobUidAnalyses
from openapi_client.apis.paths.api2_v3_project_templates_project_template_uid_pre_translate_settings import Api2V3ProjectTemplatesProjectTemplateUidPreTranslateSettings
from openapi_client.apis.paths.api2_v3_project_templates_project_template_uid_trans_memories import Api2V3ProjectTemplatesProjectTemplateUidTransMemories
from openapi_client.apis.paths.api2_v3_projects_project_uid_trans_memories import Api2V3ProjectsProjectUidTransMemories
from openapi_client.apis.paths.api2_v3_users_user_uid import Api2V3UsersUserUid
from openapi_client.apis.paths.api2_v3_users import Api2V3Users
from openapi_client.apis.paths.api2_v3_users_user_uid_disable_two_factor_auth import Api2V3UsersUserUidDisableTwoFactorAuth

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.API2_V1_ADDITIONAL_WORKFLOW_STEPS_ID: Api2V1AdditionalWorkflowStepsId,
        PathValues.API2_V1_ADDITIONAL_WORKFLOW_STEPS: Api2V1AdditionalWorkflowSteps,
        PathValues.API2_V1_ANALYSES_ANALYSE_UID: Api2V1AnalysesAnalyseUid,
        PathValues.API2_V1_ANALYSES_BULK: Api2V1AnalysesBulk,
        PathValues.API2_V1_ANALYSES_ANALYSE_UID_JOBS_JOB_UID: Api2V1AnalysesAnalyseUidJobsJobUid,
        PathValues.API2_V1_ANALYSES_ANALYSE_UID_DOWNLOAD: Api2V1AnalysesAnalyseUidDownload,
        PathValues.API2_V1_ANALYSES_RECALCULATE: Api2V1AnalysesRecalculate,
        PathValues.API2_V1_ANALYSES_ANALYSE_UID_ANALYSE_LANGUAGE_PARTS_ANALYSE_LANGUAGE_PART_ID_JOBS: Api2V1AnalysesAnalyseUidAnalyseLanguagePartsAnalyseLanguagePartIdJobs,
        PathValues.API2_V1_ANALYSES_BY_PROVIDERS: Api2V1AnalysesByProviders,
        PathValues.API2_V1_ANALYSES_BY_LANGUAGES: Api2V1AnalysesByLanguages,
        PathValues.API2_V1_ANALYSES_ANALYSE_UID_ANALYSE_LANGUAGE_PARTS_ANALYSE_LANGUAGE_PART_ID: Api2V1AnalysesAnalyseUidAnalyseLanguagePartsAnalyseLanguagePartId,
        PathValues.API2_V1_ASYNC_ASYNC_REQUEST_ID: Api2V1AsyncAsyncRequestId,
        PathValues.API2_V1_ASYNC: Api2V1Async,
        PathValues.API2_V1_ASYNC_STATUS: Api2V1AsyncStatus,
        PathValues.API2_V1_AUTH_LOGIN: Api2V1AuthLogin,
        PathValues.API2_V1_AUTH_LOGOUT: Api2V1AuthLogout,
        PathValues.API2_V1_AUTH_LOGIN_TO_SESSION: Api2V1AuthLoginToSession,
        PathValues.API2_V1_AUTH_LOGIN_OTHER: Api2V1AuthLoginOther,
        PathValues.API2_V1_AUTH_WHO_AM_I: Api2V1AuthWhoAmI,
        PathValues.API2_V1_AUTH_LOGIN_WITH_GOOGLE: Api2V1AuthLoginWithGoogle,
        PathValues.API2_V1_AUTH_LOGIN_WITH_APPLE_REFRESH_TOKEN: Api2V1AuthLoginWithAppleRefreshToken,
        PathValues.API2_V1_AUTH_LOGIN_WITH_APPLE_CODE: Api2V1AuthLoginWithAppleCode,
        PathValues.API2_V1_AUTH_REFRESH_APPLE_TOKEN: Api2V1AuthRefreshAppleToken,
        PathValues.API2_V1_BILINGUAL_FILES_CONVERT: Api2V1BilingualFilesConvert,
        PathValues.API2_V1_BILINGUAL_FILES: Api2V1BilingualFiles,
        PathValues.API2_V1_BILINGUAL_FILES_COMPARE: Api2V1BilingualFilesCompare,
        PathValues.API2_V1_BILINGUAL_FILES_PREVIEW: Api2V1BilingualFilesPreview,
        PathValues.API2_V1_BUSINESS_UNITS_BUSINESS_UNIT_UID: Api2V1BusinessUnitsBusinessUnitUid,
        PathValues.API2_V1_BUSINESS_UNITS: Api2V1BusinessUnits,
        PathValues.API2_V1_CLIENTS_CLIENT_UID: Api2V1ClientsClientUid,
        PathValues.API2_V1_CLIENTS: Api2V1Clients,
        PathValues.API2_V1_CONNECTORS_CONNECTOR_ID_FOLDERS_FOLDER_FILES_FILE: Api2V1ConnectorsConnectorIdFoldersFolderFilesFile,
        PathValues.API2_V1_CONNECTORS_CONNECTOR_ID: Api2V1ConnectorsConnectorId,
        PathValues.API2_V1_CONNECTORS: Api2V1Connectors,
        PathValues.API2_V1_CONNECTORS_CONNECTOR_ID_FOLDERS_FOLDER: Api2V1ConnectorsConnectorIdFoldersFolder,
        PathValues.API2_V1_CONNECTORS_CONNECTOR_ID_FOLDERS: Api2V1ConnectorsConnectorIdFolders,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS: Api2V1JobsJobUidConversations,
        PathValues.API2_V1_JOBS_CONVERSATIONS_FIND: Api2V1JobsConversationsFind,
        PathValues.API2_V1_COST_CENTERS_COST_CENTER_UID: Api2V1CostCentersCostCenterUid,
        PathValues.API2_V1_COST_CENTERS: Api2V1CostCenters,
        PathValues.API2_V1_CUSTOM_FIELDS_FIELD_UID: Api2V1CustomFieldsFieldUid,
        PathValues.API2_V1_CUSTOM_FIELDS: Api2V1CustomFields,
        PathValues.API2_V1_CUSTOM_FIELDS_FIELD_UID_OPTIONS: Api2V1CustomFieldsFieldUidOptions,
        PathValues.API2_V1_CUSTOM_FILE_TYPES: Api2V1CustomFileTypes,
        PathValues.API2_V1_CUSTOM_FILE_TYPES_CUSTOM_FILE_TYPE_UID: Api2V1CustomFileTypesCustomFileTypeUid,
        PathValues.API2_V1_NET_RATE_SCHEMES_NET_RATE_SCHEME_UID: Api2V1NetRateSchemesNetRateSchemeUid,
        PathValues.API2_V1_NET_RATE_SCHEMES: Api2V1NetRateSchemes,
        PathValues.API2_V1_NET_RATE_SCHEMES_NET_RATE_SCHEME_UID_WORKFLOW_STEP_NET_SCHEMES_NET_RATE_SCHEME_WORKFLOW_STEP_ID: Api2V1NetRateSchemesNetRateSchemeUidWorkflowStepNetSchemesNetRateSchemeWorkflowStepId,
        PathValues.API2_V1_NET_RATE_SCHEMES_NET_RATE_SCHEME_UID_WORKFLOW_STEP_NET_SCHEMES: Api2V1NetRateSchemesNetRateSchemeUidWorkflowStepNetSchemes,
        PathValues.API2_V1_DOMAINS_DOMAIN_UID: Api2V1DomainsDomainUid,
        PathValues.API2_V1_DOMAINS: Api2V1Domains,
        PathValues.API2_V1_EMAIL_TEMPLATES: Api2V1EmailTemplates,
        PathValues.API2_V1_EMAIL_TEMPLATES_TEMPLATE_UID: Api2V1EmailTemplatesTemplateUid,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_FILE_HANDOVERS: Api2V1ProjectsProjectUidFileHandovers,
        PathValues.API2_V1_FILES_FILE_UID: Api2V1FilesFileUid,
        PathValues.API2_V1_FILES: Api2V1Files,
        PathValues.API2_V1_GLOSSARIES_GLOSSARY_UID: Api2V1GlossariesGlossaryUid,
        PathValues.API2_V1_GLOSSARIES: Api2V1Glossaries,
        PathValues.API2_V1_GLOSSARIES_GLOSSARY_UID_ACTIVATE: Api2V1GlossariesGlossaryUidActivate,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TRANS_MEMORIES_SEARCH_SEGMENT: Api2V1ProjectsProjectUidJobsJobUidTransMemoriesSearchSegment,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS_LQAS_CONVERSATION_ID_COMMENTS_COMMENT_ID: Api2V1JobsJobUidConversationsLqasConversationIdCommentsCommentId,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS_LQAS: Api2V1JobsJobUidConversationsLqas,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS_LQAS_CONVERSATION_ID: Api2V1JobsJobUidConversationsLqasConversationId,
        PathValues.API2_V1_LANGUAGES: Api2V1Languages,
        PathValues.API2_V1_LQA_ASSESSMENTS_REPORTS: Api2V1LqaAssessmentsReports,
        PathValues.API2_V1_LQA_PROFILES_PROFILE_UID: Api2V1LqaProfilesProfileUid,
        PathValues.API2_V1_LQA_PROFILES: Api2V1LqaProfiles,
        PathValues.API2_V1_LQA_PROFILES_PROFILE_UID_DUPLICATE: Api2V1LqaProfilesProfileUidDuplicate,
        PathValues.API2_V1_LQA_PROFILES_PROFILE_UID_DEFAULT: Api2V1LqaProfilesProfileUidDefault,
        PathValues.API2_V1_LQA_PROFILES_AUTHORS: Api2V1LqaProfilesAuthors,
        PathValues.API2_V1_MACHINE_TRANSLATE_SETTINGS_MTS_UID_STATUS: Api2V1MachineTranslateSettingsMtsUidStatus,
        PathValues.API2_V1_MACHINE_TRANSLATE_SETTINGS: Api2V1MachineTranslateSettings,
        PathValues.API2_V1_MACHINE_TRANSLATE_SETTINGS_MTS_UID: Api2V1MachineTranslateSettingsMtsUid,
        PathValues.API2_V1_MACHINE_TRANSLATE_SETTINGS_TYPES: Api2V1MachineTranslateSettingsTypes,
        PathValues.API2_V1_MACHINE_TRANSLATE_SETTINGS_THIRD_PARTY_ENGINES: Api2V1MachineTranslateSettingsThirdPartyEngines,
        PathValues.API2_V1_MACHINE_TRANSLATIONS_MT_SETTINGS_UID_TRANSLATE: Api2V1MachineTranslationsMtSettingsUidTranslate,
        PathValues.API2_V1_MAPPINGS_TASKS_ID: Api2V1MappingsTasksId,
        PathValues.API2_V1_IMPORT_SETTINGS_UID: Api2V1ImportSettingsUid,
        PathValues.API2_V1_IMPORT_SETTINGS_DEFAULT: Api2V1ImportSettingsDefault,
        PathValues.API2_V1_IMPORT_SETTINGS: Api2V1ImportSettings,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS_PLAINS_CONVERSATION_ID: Api2V1JobsJobUidConversationsPlainsConversationId,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS_PLAINS: Api2V1JobsJobUidConversationsPlains,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS_PLAINS_CONVERSATION_ID_COMMENTS_COMMENT_ID: Api2V1JobsJobUidConversationsPlainsConversationIdCommentsCommentId,
        PathValues.API2_V1_PROJECTS_PROJECT_UID: Api2V1ProjectsProjectUid,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_WORKFLOW_STEPS: Api2V1ProjectsProjectUidWorkflowSteps,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_APPLY_TEMPLATE_TEMPLATE_UID_ASSIGN_PROVIDERS_FOR_JOB_PARTS: Api2V1ProjectsProjectUidApplyTemplateTemplateUidAssignProvidersForJobParts,
        PathValues.API2_V1_PROJECTS: Api2V1Projects,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_TARGET_LANGS: Api2V1ProjectsProjectUidTargetLangs,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_ASSIGN_VENDOR: Api2V1ProjectsProjectUidAssignVendor,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_CLONE: Api2V1ProjectsProjectUidClone,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_PROVIDERS: Api2V1ProjectsProjectUidProviders,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_SET_STATUS: Api2V1ProjectsProjectUidSetStatus,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_ASSIGNABLE_TEMPLATES: Api2V1ProjectsProjectUidAssignableTemplates,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_APPLY_TEMPLATE_TEMPLATE_UID_ASSIGN_PROVIDERS: Api2V1ProjectsProjectUidApplyTemplateTemplateUidAssignProviders,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_FINANCIAL_SETTINGS: Api2V1ProjectsProjectUidFinancialSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_QA_SETTINGS_CHECKS: Api2V1ProjectsProjectUidQaSettingsChecks,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_LQA_SETTINGS: Api2V1ProjectsProjectUidLqaSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_MT_SETTINGS: Api2V1ProjectsProjectUidMtSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_QUOTES: Api2V1ProjectsProjectUidQuotes,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_MT_SETTINGS_PER_LANGUAGE: Api2V1ProjectsProjectUidMtSettingsPerLanguage,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_ANALYSE_SETTINGS: Api2V1ProjectsProjectUidAnalyseSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_IMPORT_SETTINGS: Api2V1ProjectsProjectUidImportSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_FILE_NAMING_SETTINGS: Api2V1ProjectsProjectUidFileNamingSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_CUSTOM_FIELDS: Api2V1ProjectsProjectUidCustomFields,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_CUSTOM_FIELDS_FIELD_INSTANCE_UID: Api2V1ProjectsProjectUidCustomFieldsFieldInstanceUid,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_SPLIT: Api2V1ProjectsProjectUidJobsJobUidSplit,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_SET_STATUS: Api2V1ProjectsProjectUidJobsJobUidSetStatus,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID: Api2V1ProjectsProjectUidJobsJobUid,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_PSEUDO_TRANSLATE: Api2V1ProjectsProjectUidJobsJobUidPseudoTranslate,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_TRANSLATIONS: Api2V1ProjectsProjectUidJobsTranslations,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_QUALITY_ASSURANCES_IGNORED_WARNINGS: Api2V1ProjectsProjectUidJobsJobUidQualityAssurancesIgnoredWarnings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_IMPORT_SETTINGS: Api2V1ProjectsProjectUidJobsJobUidImportSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_STATUS_CHANGES: Api2V1ProjectsProjectUidJobsJobUidStatusChanges,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_COPY_SOURCE_TO_TARGET: Api2V1ProjectsProjectUidJobsCopySourceToTarget,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_COPY_SOURCE_TO_TARGET: Api2V1ProjectsProjectUidJobsJobUidCopySourceToTarget,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TRANSLATION_RESOURCES: Api2V1ProjectsProjectUidJobsJobUidTranslationResources,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_SEGMENTS: Api2V1ProjectsProjectUidJobsJobUidSegments,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_ORIGINAL: Api2V1ProjectsProjectUidJobsJobUidOriginal,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_PREVIEW: Api2V1ProjectsProjectUidJobsJobUidPreview,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TARGET_FILE_WARNINGS: Api2V1ProjectsProjectUidJobsJobUidTargetFileWarnings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_PREVIEW_URL: Api2V1ProjectsProjectUidJobsJobUidPreviewUrl,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS: Api2V1ProjectsProjectUidJobs,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_CONNECTOR_TASK: Api2V1ProjectsProjectUidJobsConnectorTask,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_SOURCE: Api2V1ProjectsProjectUidJobsSource,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_TARGET: Api2V1ProjectsProjectUidJobsTarget,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_BATCH: Api2V1ProjectsProjectUidJobsBatch,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_HUMAN_TRANSLATE: Api2V1ProjectsProjectUidJobsHumanTranslate,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_NOTIFY_ASSIGNED: Api2V1ProjectsProjectUidJobsNotifyAssigned,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_COMPARE: Api2V1ProjectsProjectUidJobsCompare,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_BILINGUAL_FILE: Api2V1ProjectsProjectUidJobsBilingualFile,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_QUALITY_ASSURANCES_IGNORE_CHECKS: Api2V1ProjectsProjectUidJobsJobUidQualityAssurancesIgnoreChecks,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_WORKFLOW_STEP: Api2V1ProjectsProjectUidJobsJobUidWorkflowStep,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_SEARCH: Api2V1ProjectsProjectUidJobsSearch,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_SEGMENTS_COUNT: Api2V1ProjectsProjectUidJobsSegmentsCount,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TERM_BASES_CREATE_BY_JOB: Api2V1ProjectsProjectUidJobsJobUidTermBasesCreateByJob,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_REFERENCES_CREATORS: Api2V1ProjectsProjectUidReferencesCreators,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_REFERENCES: Api2V1ProjectsProjectUidReferences,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_REFERENCES_REFERENCE_FILE_ID: Api2V1ProjectsProjectUidReferencesReferenceFileId,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_REFERENCES_DOWNLOAD: Api2V1ProjectsProjectUidReferencesDownload,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_TRANS_MEMORIES_RELEVANT: Api2V1ProjectTemplatesProjectTemplateUidTransMemoriesRelevant,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_QA_SETTINGS: Api2V1ProjectTemplatesProjectTemplateUidQaSettings,
        PathValues.API2_V1_PROJECT_TEMPLATES: Api2V1ProjectTemplates,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID: Api2V1ProjectTemplatesProjectTemplateUid,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_ANALYSE_SETTINGS: Api2V1ProjectTemplatesProjectTemplateUidAnalyseSettings,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_IMPORT_SETTINGS: Api2V1ProjectTemplatesProjectTemplateUidImportSettings,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_MT_SETTINGS: Api2V1ProjectTemplatesProjectTemplateUidMtSettings,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_TERM_BASES: Api2V1ProjectTemplatesProjectTemplateUidTermBases,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_ACCESS_SETTINGS: Api2V1ProjectTemplatesProjectTemplateUidAccessSettings,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_CUSTOM_FIELDS: Api2V1ProjectTemplatesProjectTemplateUidCustomFields,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_CUSTOM_FIELDS_FIELD_INSTANCE_UID: Api2V1ProjectTemplatesProjectTemplateUidCustomFieldsFieldInstanceUid,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_TERM_BASES: Api2V1ProjectsProjectUidTermBases,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_TERM_BASES_RELEVANT: Api2V1ProjectsProjectUidTermBasesRelevant,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_TRANS_MEMORIES_RELEVANT: Api2V1ProjectsProjectUidTransMemoriesRelevant,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_TRANS_MEMORIES_SEARCH_SEGMENT_IN_PROJECT: Api2V1ProjectsProjectUidTransMemoriesSearchSegmentInProject,
        PathValues.API2_V1_QUOTES_QUOTE_UID: Api2V1QuotesQuoteUid,
        PathValues.API2_V1_QUOTES_EMAIL: Api2V1QuotesEmail,
        PathValues.API2_V1_SCIM_RESOURCE_TYPES: Api2V1ScimResourceTypes,
        PathValues.API2_V1_SCIM_SCHEMAS: Api2V1ScimSchemas,
        PathValues.API2_V1_SCIM_SERVICE_PROVIDER_CONFIG: Api2V1ScimServiceProviderConfig,
        PathValues.API2_V1_SCIM_SCHEMAS_SCHEMA_URN: Api2V1ScimSchemasSchemaUrn,
        PathValues.API2_V1_SCIM_USERS_USER_ID: Api2V1ScimUsersUserId,
        PathValues.API2_V1_SCIM_USERS: Api2V1ScimUsers,
        PathValues.API2_V1_SEGMENTATION_RULES_SEG_RULE_ID: Api2V1SegmentationRulesSegRuleId,
        PathValues.API2_V1_SEGMENTATION_RULES: Api2V1SegmentationRules,
        PathValues.API2_V1_SPELL_CHECK_CHECK: Api2V1SpellCheckCheck,
        PathValues.API2_V1_SPELL_CHECK_CHECK_JOB_UID: Api2V1SpellCheckCheckJobUid,
        PathValues.API2_V1_SPELL_CHECK_WORDS: Api2V1SpellCheckWords,
        PathValues.API2_V1_SPELL_CHECK_SUGGEST: Api2V1SpellCheckSuggest,
        PathValues.API2_V1_SUB_DOMAINS_SUB_DOMAIN_UID: Api2V1SubDomainsSubDomainUid,
        PathValues.API2_V1_SUB_DOMAINS: Api2V1SubDomains,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID: Api2V1TermBasesTermBaseUid,
        PathValues.API2_V1_TERM_BASES: Api2V1TermBases,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_UPLOAD: Api2V1TermBasesTermBaseUidUpload,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_CONCEPTS: Api2V1TermBasesTermBaseUidConcepts,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_CONCEPTS_CONCEPT_UID: Api2V1TermBasesTermBaseUidConceptsConceptUid,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_TERMS: Api2V1TermBasesTermBaseUidTerms,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_TERMS_TERM_ID: Api2V1TermBasesTermBaseUidTermsTermId,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_CONCEPTS_CONCEPT_ID: Api2V1TermBasesTermBaseUidConceptsConceptId,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_CONCEPTS_CONCEPT_ID_TERMS: Api2V1TermBasesTermBaseUidConceptsConceptIdTerms,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_LAST_BACKGROUND_TASK: Api2V1TermBasesTermBaseUidLastBackgroundTask,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_BROWSE: Api2V1TermBasesTermBaseUidBrowse,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_SEARCH: Api2V1TermBasesTermBaseUidSearch,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_EXPORT: Api2V1TermBasesTermBaseUidExport,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_METADATA: Api2V1TermBasesTermBaseUidMetadata,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_SEARCH: Api2V1TransMemoriesTransMemoryUidSearch,
        PathValues.API2_V1_TRANS_MEMORIES: Api2V1TransMemories,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID: Api2V1TransMemoriesTransMemoryUid,
        PathValues.API2_V1_TRANS_MEMORIES_EXTRACT_CLEANED: Api2V1TransMemoriesExtractCleaned,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_TARGET_LANGUAGES: Api2V1TransMemoriesTransMemoryUidTargetLanguages,
        PathValues.API2_V1_TRANS_MEMORIES_DOWNLOAD_CLEANED_ASYNC_REQUEST_ID: Api2V1TransMemoriesDownloadCleanedAsyncRequestId,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_SEGMENTS: Api2V1TransMemoriesTransMemoryUidSegments,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_RELATED_PROJECTS: Api2V1TransMemoriesTransMemoryUidRelatedProjects,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_METADATA: Api2V1TransMemoriesTransMemoryUidMetadata,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_SEGMENTS_SEGMENT_ID: Api2V1TransMemoriesTransMemoryUidSegmentsSegmentId,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_SEGMENTS_SEGMENT_ID_LANG_LANG: Api2V1TransMemoriesTransMemoryUidSegmentsSegmentIdLangLang,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_LAST_BACKGROUND_TASK: Api2V1TransMemoriesTransMemoryUidLastBackgroundTask,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_WILD_CARD_SEARCH: Api2V1TransMemoriesTransMemoryUidWildCardSearch,
        PathValues.API2_V1_TRANS_MEMORIES_DOWNLOAD_EXPORT_ASYNC_REQUEST_ID: Api2V1TransMemoriesDownloadExportAsyncRequestId,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_EXPORT_BY_QUERY_ASYNC: Api2V1TransMemoriesTransMemoryUidExportByQueryAsync,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TRANSLATIONS_TRANSLATE_WITH_MACHINE_TRANSLATION: Api2V1ProjectsProjectUidJobsJobUidTranslationsTranslateWithMachineTranslation,
        PathValues.API2_V1_PRICE_LISTS_PRICE_LIST_UID: Api2V1PriceListsPriceListUid,
        PathValues.API2_V1_PRICE_LISTS: Api2V1PriceLists,
        PathValues.API2_V1_PRICE_LISTS_PRICE_LIST_UID_PRICE_SETS: Api2V1PriceListsPriceListUidPriceSets,
        PathValues.API2_V1_PRICE_LISTS_PRICE_LIST_UID_PRICE_SETS_SOURCE_LANGUAGE_TARGET_LANGUAGE: Api2V1PriceListsPriceListUidPriceSetsSourceLanguageTargetLanguage,
        PathValues.API2_V1_PRICE_LISTS_PRICE_LIST_UID_PRICE_SETS_MINIMUM_PRICES: Api2V1PriceListsPriceListUidPriceSetsMinimumPrices,
        PathValues.API2_V1_PRICE_LISTS_PRICE_LIST_UID_PRICE_SETS_PRICES: Api2V1PriceListsPriceListUidPriceSetsPrices,
        PathValues.API2_V1_USERS_USER_UID: Api2V1UsersUserUid,
        PathValues.API2_V1_USERS_USER_UID_PROJECTS: Api2V1UsersUserUidProjects,
        PathValues.API2_V1_USERS_LAST_LOGINS: Api2V1UsersLastLogins,
        PathValues.API2_V1_USERS_USER_UID_JOBS: Api2V1UsersUserUidJobs,
        PathValues.API2_V1_USERS: Api2V1Users,
        PathValues.API2_V1_USERS_USER_UID_UPDATE_PASSWORD: Api2V1UsersUserUidUpdatePassword,
        PathValues.API2_V1_USERS_USER_UID_EMAIL_LOGIN_INFORMATION: Api2V1UsersUserUidEmailLoginInformation,
        PathValues.API2_V1_USERS_USER_UID_UNDELETE: Api2V1UsersUserUidUndelete,
        PathValues.API2_V1_USERS_USER_UID_LOGIN_STATISTICS: Api2V1UsersUserUidLoginStatistics,
        PathValues.API2_V1_USERS_USER_UID_WORKFLOW_STEPS: Api2V1UsersUserUidWorkflowSteps,
        PathValues.API2_V1_USERS_USER_UID_TARGET_LANGS: Api2V1UsersUserUidTargetLangs,
        PathValues.API2_V1_VENDORS_VENDOR_UID: Api2V1VendorsVendorUid,
        PathValues.API2_V1_VENDORS: Api2V1Vendors,
        PathValues.API2_V1_WEBHOOKS_CALLS_REPLAY_LATEST: Api2V1WebhooksCallsReplayLatest,
        PathValues.API2_V1_WEBHOOKS_CALLS: Api2V1WebhooksCalls,
        PathValues.API2_V1_WEBHOOKS_CALLS_REPLAY: Api2V1WebhooksCallsReplay,
        PathValues.API2_V1_WORKFLOW_STEPS: Api2V1WorkflowSteps,
        PathValues.API2_V1_WORKFLOW_STEPS_WORKFLOW_STEP_UID: Api2V1WorkflowStepsWorkflowStepUid,
        PathValues.API2_V2_ANALYSES_ANALYSE_UID: Api2V2AnalysesAnalyseUid,
        PathValues.API2_V2_ANALYSES: Api2V2Analyses,
        PathValues.API2_V2_ANALYSES_BULK: Api2V2AnalysesBulk,
        PathValues.API2_V2_CONNECTORS_CONNECTOR_ID_FOLDERS_FOLDER_FILES_FILE: Api2V2ConnectorsConnectorIdFoldersFolderFilesFile,
        PathValues.API2_V2_CONNECTORS_CONNECTOR_ID_FOLDERS_FOLDER_FILES_FILE_NAME_UPLOAD: Api2V2ConnectorsConnectorIdFoldersFolderFilesFileNameUpload,
        PathValues.API2_V2_CONNECTORS_CONNECTOR_ID_FOLDERS_FOLDER_FILES_FILE_TASKS_TASK_ID: Api2V2ConnectorsConnectorIdFoldersFolderFilesFileTasksTaskId,
        PathValues.API2_V2_JOBS_WORKFLOW_CHANGES: Api2V2JobsWorkflowChanges,
        PathValues.API2_V2_JOBS_JOB_UID_CONVERSATIONS_LQAS: Api2V2JobsJobUidConversationsLqas,
        PathValues.API2_V2_JOBS_JOB_UID_CONVERSATIONS_LQAS_CONVERSATION_ID: Api2V2JobsJobUidConversationsLqasConversationId,
        PathValues.API2_V2_JOBS_JOB_UID_CONVERSATIONS_LQAS_CONVERSATION_ID_COMMENTS: Api2V2JobsJobUidConversationsLqasConversationIdComments,
        PathValues.API2_V2_JOBS_JOB_UID_CONVERSATIONS_LQAS_CONVERSATION_ID_COMMENTS_COMMENT_ID: Api2V2JobsJobUidConversationsLqasConversationIdCommentsCommentId,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_PROVIDERS_SUGGEST: Api2V2ProjectsProjectUidProvidersSuggest,
        PathValues.API2_V2_PROJECTS_APPLY_TEMPLATE_ASYNC_TEMPLATE_UID: Api2V2ProjectsApplyTemplateAsyncTemplateUid,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_ACCESS_SETTINGS: Api2V2ProjectsProjectUidAccessSettings,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_WORKFLOW_STEPS: Api2V2ProjectsProjectUidWorkflowSteps,
        PathValues.API2_V2_PROJECTS_PROJECT_UID: Api2V2ProjectsProjectUid,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_QA_SETTINGS: Api2V2ProjectsProjectUidQaSettings,
        PathValues.API2_V2_PROJECTS_APPLY_TEMPLATE_TEMPLATE_UID: Api2V2ProjectsApplyTemplateTemplateUid,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS: Api2V2ProjectsProjectUidJobs,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_JOB_UID_QUALITY_ASSURANCES_SETTINGS: Api2V2ProjectsProjectUidJobsJobUidQualityAssurancesSettings,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_QUALITY_ASSURANCES_SETTINGS: Api2V2ProjectsProjectUidJobsQualityAssurancesSettings,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_WEB_EDITOR: Api2V2ProjectsProjectUidJobsWebEditor,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_PSEUDO_TRANSLATE: Api2V2ProjectsProjectUidJobsPseudoTranslate,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_PRE_TRANSLATE: Api2V2ProjectsProjectUidJobsPreTranslate,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_TRANSLATIONS: Api2V2ProjectsProjectUidJobsTranslations,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_JOB_UID_PROVIDERS_SUGGEST: Api2V2ProjectsProjectUidJobsJobUidProvidersSuggest,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TARGET_FILE: Api2V2ProjectsProjectUidJobsJobUidTargetFile,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_JOB_UID_DOWNLOAD_TARGET_FILE_ASYNC_REQUEST_ID: Api2V2ProjectsProjectUidJobsJobUidDownloadTargetFileAsyncRequestId,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_QUALITY_ASSURANCES_IGNORED_WARNINGS: Api2V2ProjectsProjectUidJobsQualityAssurancesIgnoredWarnings,
        PathValues.API2_V2_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_TRANS_MEMORIES: Api2V2ProjectTemplatesProjectTemplateUidTransMemories,
        PathValues.API2_V2_QUOTES: Api2V2Quotes,
        PathValues.API2_V2_TRANS_MEMORIES_TRANS_MEMORY_UID_EXPORT: Api2V2TransMemoriesTransMemoryUidExport,
        PathValues.API2_V2_TRANS_MEMORIES_TRANS_MEMORY_UID_SEGMENTS: Api2V2TransMemoriesTransMemoryUidSegments,
        PathValues.API2_V2_TRANS_MEMORIES_TRANS_MEMORY_UID_IMPORT: Api2V2TransMemoriesTransMemoryUidImport,
        PathValues.API2_V2_WEBHOOKS_WEB_HOOK_UID: Api2V2WebhooksWebHookUid,
        PathValues.API2_V2_WEBHOOKS: Api2V2Webhooks,
        PathValues.API2_V2_WEBHOOKS_PREVIEWS: Api2V2WebhooksPreviews,
        PathValues.API2_V2_WEBHOOKS_WEBHOOK_UID_TEST: Api2V2WebhooksWebhookUidTest,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TERM_BASES_SEARCH_BY_JOB: Api2V2ProjectsProjectUidJobsJobUidTermBasesSearchByJob,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TERM_BASES_SEARCH_IN_TEXT_BY_JOB: Api2V2ProjectsProjectUidJobsJobUidTermBasesSearchInTextByJob,
        PathValues.API2_V3_ANALYSES_ANALYSE_UID: Api2V3AnalysesAnalyseUid,
        PathValues.API2_V3_AUTH_LOGIN: Api2V3AuthLogin,
        PathValues.API2_V3_AUTH_LOGIN_TO_SESSION: Api2V3AuthLoginToSession,
        PathValues.API2_V3_AUTH_LOGIN_OTHER: Api2V3AuthLoginOther,
        PathValues.API2_V3_JOBS: Api2V3Jobs,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TRANS_MEMORIES_SEARCH: Api2V3ProjectsProjectUidJobsJobUidTransMemoriesSearch,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TRANS_MEMORIES_WILD_CARD_SEARCH: Api2V3ProjectsProjectUidJobsJobUidTransMemoriesWildCardSearch,
        PathValues.API2_V3_JOBS_JOB_UID_CONVERSATIONS_PLAINS_CONVERSATION_ID_COMMENTS: Api2V3JobsJobUidConversationsPlainsConversationIdComments,
        PathValues.API2_V3_JOBS_JOB_UID_CONVERSATIONS_PLAINS: Api2V3JobsJobUidConversationsPlains,
        PathValues.API2_V3_JOBS_JOB_UID_CONVERSATIONS_PLAINS_CONVERSATION_ID_COMMENTS_COMMENT_ID: Api2V3JobsJobUidConversationsPlainsConversationIdCommentsCommentId,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_PRE_TRANSLATE_SETTINGS: Api2V3ProjectsProjectUidPreTranslateSettings,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_ANALYSES: Api2V3ProjectsProjectUidAnalyses,
        PathValues.API2_V3_PROJECTS: Api2V3Projects,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_EXPORT: Api2V3ProjectsProjectUidJobsExport,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_JOB_UID_QUALITY_ASSURANCES_RUN: Api2V3ProjectsProjectUidJobsJobUidQualityAssurancesRun,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_QUALITY_ASSURANCES_RUN: Api2V3ProjectsProjectUidJobsQualityAssurancesRun,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_QUALITY_ASSURANCES_SEGMENTS_RUN: Api2V3ProjectsProjectUidJobsQualityAssurancesSegmentsRun,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_JOB_UID_ANALYSES: Api2V3ProjectsProjectUidJobsJobUidAnalyses,
        PathValues.API2_V3_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_PRE_TRANSLATE_SETTINGS: Api2V3ProjectTemplatesProjectTemplateUidPreTranslateSettings,
        PathValues.API2_V3_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_TRANS_MEMORIES: Api2V3ProjectTemplatesProjectTemplateUidTransMemories,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_TRANS_MEMORIES: Api2V3ProjectsProjectUidTransMemories,
        PathValues.API2_V3_USERS_USER_UID: Api2V3UsersUserUid,
        PathValues.API2_V3_USERS: Api2V3Users,
        PathValues.API2_V3_USERS_USER_UID_DISABLE_TWO_FACTOR_AUTH: Api2V3UsersUserUidDisableTwoFactorAuth,
    }
)

path_to_api = PathToApi(
    {
        PathValues.API2_V1_ADDITIONAL_WORKFLOW_STEPS_ID: Api2V1AdditionalWorkflowStepsId,
        PathValues.API2_V1_ADDITIONAL_WORKFLOW_STEPS: Api2V1AdditionalWorkflowSteps,
        PathValues.API2_V1_ANALYSES_ANALYSE_UID: Api2V1AnalysesAnalyseUid,
        PathValues.API2_V1_ANALYSES_BULK: Api2V1AnalysesBulk,
        PathValues.API2_V1_ANALYSES_ANALYSE_UID_JOBS_JOB_UID: Api2V1AnalysesAnalyseUidJobsJobUid,
        PathValues.API2_V1_ANALYSES_ANALYSE_UID_DOWNLOAD: Api2V1AnalysesAnalyseUidDownload,
        PathValues.API2_V1_ANALYSES_RECALCULATE: Api2V1AnalysesRecalculate,
        PathValues.API2_V1_ANALYSES_ANALYSE_UID_ANALYSE_LANGUAGE_PARTS_ANALYSE_LANGUAGE_PART_ID_JOBS: Api2V1AnalysesAnalyseUidAnalyseLanguagePartsAnalyseLanguagePartIdJobs,
        PathValues.API2_V1_ANALYSES_BY_PROVIDERS: Api2V1AnalysesByProviders,
        PathValues.API2_V1_ANALYSES_BY_LANGUAGES: Api2V1AnalysesByLanguages,
        PathValues.API2_V1_ANALYSES_ANALYSE_UID_ANALYSE_LANGUAGE_PARTS_ANALYSE_LANGUAGE_PART_ID: Api2V1AnalysesAnalyseUidAnalyseLanguagePartsAnalyseLanguagePartId,
        PathValues.API2_V1_ASYNC_ASYNC_REQUEST_ID: Api2V1AsyncAsyncRequestId,
        PathValues.API2_V1_ASYNC: Api2V1Async,
        PathValues.API2_V1_ASYNC_STATUS: Api2V1AsyncStatus,
        PathValues.API2_V1_AUTH_LOGIN: Api2V1AuthLogin,
        PathValues.API2_V1_AUTH_LOGOUT: Api2V1AuthLogout,
        PathValues.API2_V1_AUTH_LOGIN_TO_SESSION: Api2V1AuthLoginToSession,
        PathValues.API2_V1_AUTH_LOGIN_OTHER: Api2V1AuthLoginOther,
        PathValues.API2_V1_AUTH_WHO_AM_I: Api2V1AuthWhoAmI,
        PathValues.API2_V1_AUTH_LOGIN_WITH_GOOGLE: Api2V1AuthLoginWithGoogle,
        PathValues.API2_V1_AUTH_LOGIN_WITH_APPLE_REFRESH_TOKEN: Api2V1AuthLoginWithAppleRefreshToken,
        PathValues.API2_V1_AUTH_LOGIN_WITH_APPLE_CODE: Api2V1AuthLoginWithAppleCode,
        PathValues.API2_V1_AUTH_REFRESH_APPLE_TOKEN: Api2V1AuthRefreshAppleToken,
        PathValues.API2_V1_BILINGUAL_FILES_CONVERT: Api2V1BilingualFilesConvert,
        PathValues.API2_V1_BILINGUAL_FILES: Api2V1BilingualFiles,
        PathValues.API2_V1_BILINGUAL_FILES_COMPARE: Api2V1BilingualFilesCompare,
        PathValues.API2_V1_BILINGUAL_FILES_PREVIEW: Api2V1BilingualFilesPreview,
        PathValues.API2_V1_BUSINESS_UNITS_BUSINESS_UNIT_UID: Api2V1BusinessUnitsBusinessUnitUid,
        PathValues.API2_V1_BUSINESS_UNITS: Api2V1BusinessUnits,
        PathValues.API2_V1_CLIENTS_CLIENT_UID: Api2V1ClientsClientUid,
        PathValues.API2_V1_CLIENTS: Api2V1Clients,
        PathValues.API2_V1_CONNECTORS_CONNECTOR_ID_FOLDERS_FOLDER_FILES_FILE: Api2V1ConnectorsConnectorIdFoldersFolderFilesFile,
        PathValues.API2_V1_CONNECTORS_CONNECTOR_ID: Api2V1ConnectorsConnectorId,
        PathValues.API2_V1_CONNECTORS: Api2V1Connectors,
        PathValues.API2_V1_CONNECTORS_CONNECTOR_ID_FOLDERS_FOLDER: Api2V1ConnectorsConnectorIdFoldersFolder,
        PathValues.API2_V1_CONNECTORS_CONNECTOR_ID_FOLDERS: Api2V1ConnectorsConnectorIdFolders,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS: Api2V1JobsJobUidConversations,
        PathValues.API2_V1_JOBS_CONVERSATIONS_FIND: Api2V1JobsConversationsFind,
        PathValues.API2_V1_COST_CENTERS_COST_CENTER_UID: Api2V1CostCentersCostCenterUid,
        PathValues.API2_V1_COST_CENTERS: Api2V1CostCenters,
        PathValues.API2_V1_CUSTOM_FIELDS_FIELD_UID: Api2V1CustomFieldsFieldUid,
        PathValues.API2_V1_CUSTOM_FIELDS: Api2V1CustomFields,
        PathValues.API2_V1_CUSTOM_FIELDS_FIELD_UID_OPTIONS: Api2V1CustomFieldsFieldUidOptions,
        PathValues.API2_V1_CUSTOM_FILE_TYPES: Api2V1CustomFileTypes,
        PathValues.API2_V1_CUSTOM_FILE_TYPES_CUSTOM_FILE_TYPE_UID: Api2V1CustomFileTypesCustomFileTypeUid,
        PathValues.API2_V1_NET_RATE_SCHEMES_NET_RATE_SCHEME_UID: Api2V1NetRateSchemesNetRateSchemeUid,
        PathValues.API2_V1_NET_RATE_SCHEMES: Api2V1NetRateSchemes,
        PathValues.API2_V1_NET_RATE_SCHEMES_NET_RATE_SCHEME_UID_WORKFLOW_STEP_NET_SCHEMES_NET_RATE_SCHEME_WORKFLOW_STEP_ID: Api2V1NetRateSchemesNetRateSchemeUidWorkflowStepNetSchemesNetRateSchemeWorkflowStepId,
        PathValues.API2_V1_NET_RATE_SCHEMES_NET_RATE_SCHEME_UID_WORKFLOW_STEP_NET_SCHEMES: Api2V1NetRateSchemesNetRateSchemeUidWorkflowStepNetSchemes,
        PathValues.API2_V1_DOMAINS_DOMAIN_UID: Api2V1DomainsDomainUid,
        PathValues.API2_V1_DOMAINS: Api2V1Domains,
        PathValues.API2_V1_EMAIL_TEMPLATES: Api2V1EmailTemplates,
        PathValues.API2_V1_EMAIL_TEMPLATES_TEMPLATE_UID: Api2V1EmailTemplatesTemplateUid,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_FILE_HANDOVERS: Api2V1ProjectsProjectUidFileHandovers,
        PathValues.API2_V1_FILES_FILE_UID: Api2V1FilesFileUid,
        PathValues.API2_V1_FILES: Api2V1Files,
        PathValues.API2_V1_GLOSSARIES_GLOSSARY_UID: Api2V1GlossariesGlossaryUid,
        PathValues.API2_V1_GLOSSARIES: Api2V1Glossaries,
        PathValues.API2_V1_GLOSSARIES_GLOSSARY_UID_ACTIVATE: Api2V1GlossariesGlossaryUidActivate,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TRANS_MEMORIES_SEARCH_SEGMENT: Api2V1ProjectsProjectUidJobsJobUidTransMemoriesSearchSegment,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS_LQAS_CONVERSATION_ID_COMMENTS_COMMENT_ID: Api2V1JobsJobUidConversationsLqasConversationIdCommentsCommentId,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS_LQAS: Api2V1JobsJobUidConversationsLqas,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS_LQAS_CONVERSATION_ID: Api2V1JobsJobUidConversationsLqasConversationId,
        PathValues.API2_V1_LANGUAGES: Api2V1Languages,
        PathValues.API2_V1_LQA_ASSESSMENTS_REPORTS: Api2V1LqaAssessmentsReports,
        PathValues.API2_V1_LQA_PROFILES_PROFILE_UID: Api2V1LqaProfilesProfileUid,
        PathValues.API2_V1_LQA_PROFILES: Api2V1LqaProfiles,
        PathValues.API2_V1_LQA_PROFILES_PROFILE_UID_DUPLICATE: Api2V1LqaProfilesProfileUidDuplicate,
        PathValues.API2_V1_LQA_PROFILES_PROFILE_UID_DEFAULT: Api2V1LqaProfilesProfileUidDefault,
        PathValues.API2_V1_LQA_PROFILES_AUTHORS: Api2V1LqaProfilesAuthors,
        PathValues.API2_V1_MACHINE_TRANSLATE_SETTINGS_MTS_UID_STATUS: Api2V1MachineTranslateSettingsMtsUidStatus,
        PathValues.API2_V1_MACHINE_TRANSLATE_SETTINGS: Api2V1MachineTranslateSettings,
        PathValues.API2_V1_MACHINE_TRANSLATE_SETTINGS_MTS_UID: Api2V1MachineTranslateSettingsMtsUid,
        PathValues.API2_V1_MACHINE_TRANSLATE_SETTINGS_TYPES: Api2V1MachineTranslateSettingsTypes,
        PathValues.API2_V1_MACHINE_TRANSLATE_SETTINGS_THIRD_PARTY_ENGINES: Api2V1MachineTranslateSettingsThirdPartyEngines,
        PathValues.API2_V1_MACHINE_TRANSLATIONS_MT_SETTINGS_UID_TRANSLATE: Api2V1MachineTranslationsMtSettingsUidTranslate,
        PathValues.API2_V1_MAPPINGS_TASKS_ID: Api2V1MappingsTasksId,
        PathValues.API2_V1_IMPORT_SETTINGS_UID: Api2V1ImportSettingsUid,
        PathValues.API2_V1_IMPORT_SETTINGS_DEFAULT: Api2V1ImportSettingsDefault,
        PathValues.API2_V1_IMPORT_SETTINGS: Api2V1ImportSettings,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS_PLAINS_CONVERSATION_ID: Api2V1JobsJobUidConversationsPlainsConversationId,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS_PLAINS: Api2V1JobsJobUidConversationsPlains,
        PathValues.API2_V1_JOBS_JOB_UID_CONVERSATIONS_PLAINS_CONVERSATION_ID_COMMENTS_COMMENT_ID: Api2V1JobsJobUidConversationsPlainsConversationIdCommentsCommentId,
        PathValues.API2_V1_PROJECTS_PROJECT_UID: Api2V1ProjectsProjectUid,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_WORKFLOW_STEPS: Api2V1ProjectsProjectUidWorkflowSteps,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_APPLY_TEMPLATE_TEMPLATE_UID_ASSIGN_PROVIDERS_FOR_JOB_PARTS: Api2V1ProjectsProjectUidApplyTemplateTemplateUidAssignProvidersForJobParts,
        PathValues.API2_V1_PROJECTS: Api2V1Projects,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_TARGET_LANGS: Api2V1ProjectsProjectUidTargetLangs,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_ASSIGN_VENDOR: Api2V1ProjectsProjectUidAssignVendor,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_CLONE: Api2V1ProjectsProjectUidClone,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_PROVIDERS: Api2V1ProjectsProjectUidProviders,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_SET_STATUS: Api2V1ProjectsProjectUidSetStatus,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_ASSIGNABLE_TEMPLATES: Api2V1ProjectsProjectUidAssignableTemplates,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_APPLY_TEMPLATE_TEMPLATE_UID_ASSIGN_PROVIDERS: Api2V1ProjectsProjectUidApplyTemplateTemplateUidAssignProviders,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_FINANCIAL_SETTINGS: Api2V1ProjectsProjectUidFinancialSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_QA_SETTINGS_CHECKS: Api2V1ProjectsProjectUidQaSettingsChecks,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_LQA_SETTINGS: Api2V1ProjectsProjectUidLqaSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_MT_SETTINGS: Api2V1ProjectsProjectUidMtSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_QUOTES: Api2V1ProjectsProjectUidQuotes,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_MT_SETTINGS_PER_LANGUAGE: Api2V1ProjectsProjectUidMtSettingsPerLanguage,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_ANALYSE_SETTINGS: Api2V1ProjectsProjectUidAnalyseSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_IMPORT_SETTINGS: Api2V1ProjectsProjectUidImportSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_FILE_NAMING_SETTINGS: Api2V1ProjectsProjectUidFileNamingSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_CUSTOM_FIELDS: Api2V1ProjectsProjectUidCustomFields,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_CUSTOM_FIELDS_FIELD_INSTANCE_UID: Api2V1ProjectsProjectUidCustomFieldsFieldInstanceUid,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_SPLIT: Api2V1ProjectsProjectUidJobsJobUidSplit,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_SET_STATUS: Api2V1ProjectsProjectUidJobsJobUidSetStatus,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID: Api2V1ProjectsProjectUidJobsJobUid,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_PSEUDO_TRANSLATE: Api2V1ProjectsProjectUidJobsJobUidPseudoTranslate,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_TRANSLATIONS: Api2V1ProjectsProjectUidJobsTranslations,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_QUALITY_ASSURANCES_IGNORED_WARNINGS: Api2V1ProjectsProjectUidJobsJobUidQualityAssurancesIgnoredWarnings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_IMPORT_SETTINGS: Api2V1ProjectsProjectUidJobsJobUidImportSettings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_STATUS_CHANGES: Api2V1ProjectsProjectUidJobsJobUidStatusChanges,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_COPY_SOURCE_TO_TARGET: Api2V1ProjectsProjectUidJobsCopySourceToTarget,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_COPY_SOURCE_TO_TARGET: Api2V1ProjectsProjectUidJobsJobUidCopySourceToTarget,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TRANSLATION_RESOURCES: Api2V1ProjectsProjectUidJobsJobUidTranslationResources,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_SEGMENTS: Api2V1ProjectsProjectUidJobsJobUidSegments,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_ORIGINAL: Api2V1ProjectsProjectUidJobsJobUidOriginal,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_PREVIEW: Api2V1ProjectsProjectUidJobsJobUidPreview,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TARGET_FILE_WARNINGS: Api2V1ProjectsProjectUidJobsJobUidTargetFileWarnings,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_PREVIEW_URL: Api2V1ProjectsProjectUidJobsJobUidPreviewUrl,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS: Api2V1ProjectsProjectUidJobs,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_CONNECTOR_TASK: Api2V1ProjectsProjectUidJobsConnectorTask,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_SOURCE: Api2V1ProjectsProjectUidJobsSource,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_TARGET: Api2V1ProjectsProjectUidJobsTarget,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_BATCH: Api2V1ProjectsProjectUidJobsBatch,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_HUMAN_TRANSLATE: Api2V1ProjectsProjectUidJobsHumanTranslate,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_NOTIFY_ASSIGNED: Api2V1ProjectsProjectUidJobsNotifyAssigned,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_COMPARE: Api2V1ProjectsProjectUidJobsCompare,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_BILINGUAL_FILE: Api2V1ProjectsProjectUidJobsBilingualFile,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_QUALITY_ASSURANCES_IGNORE_CHECKS: Api2V1ProjectsProjectUidJobsJobUidQualityAssurancesIgnoreChecks,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_WORKFLOW_STEP: Api2V1ProjectsProjectUidJobsJobUidWorkflowStep,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_SEARCH: Api2V1ProjectsProjectUidJobsSearch,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_SEGMENTS_COUNT: Api2V1ProjectsProjectUidJobsSegmentsCount,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TERM_BASES_CREATE_BY_JOB: Api2V1ProjectsProjectUidJobsJobUidTermBasesCreateByJob,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_REFERENCES_CREATORS: Api2V1ProjectsProjectUidReferencesCreators,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_REFERENCES: Api2V1ProjectsProjectUidReferences,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_REFERENCES_REFERENCE_FILE_ID: Api2V1ProjectsProjectUidReferencesReferenceFileId,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_REFERENCES_DOWNLOAD: Api2V1ProjectsProjectUidReferencesDownload,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_TRANS_MEMORIES_RELEVANT: Api2V1ProjectTemplatesProjectTemplateUidTransMemoriesRelevant,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_QA_SETTINGS: Api2V1ProjectTemplatesProjectTemplateUidQaSettings,
        PathValues.API2_V1_PROJECT_TEMPLATES: Api2V1ProjectTemplates,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID: Api2V1ProjectTemplatesProjectTemplateUid,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_ANALYSE_SETTINGS: Api2V1ProjectTemplatesProjectTemplateUidAnalyseSettings,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_IMPORT_SETTINGS: Api2V1ProjectTemplatesProjectTemplateUidImportSettings,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_MT_SETTINGS: Api2V1ProjectTemplatesProjectTemplateUidMtSettings,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_TERM_BASES: Api2V1ProjectTemplatesProjectTemplateUidTermBases,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_ACCESS_SETTINGS: Api2V1ProjectTemplatesProjectTemplateUidAccessSettings,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_CUSTOM_FIELDS: Api2V1ProjectTemplatesProjectTemplateUidCustomFields,
        PathValues.API2_V1_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_CUSTOM_FIELDS_FIELD_INSTANCE_UID: Api2V1ProjectTemplatesProjectTemplateUidCustomFieldsFieldInstanceUid,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_TERM_BASES: Api2V1ProjectsProjectUidTermBases,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_TERM_BASES_RELEVANT: Api2V1ProjectsProjectUidTermBasesRelevant,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_TRANS_MEMORIES_RELEVANT: Api2V1ProjectsProjectUidTransMemoriesRelevant,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_TRANS_MEMORIES_SEARCH_SEGMENT_IN_PROJECT: Api2V1ProjectsProjectUidTransMemoriesSearchSegmentInProject,
        PathValues.API2_V1_QUOTES_QUOTE_UID: Api2V1QuotesQuoteUid,
        PathValues.API2_V1_QUOTES_EMAIL: Api2V1QuotesEmail,
        PathValues.API2_V1_SCIM_RESOURCE_TYPES: Api2V1ScimResourceTypes,
        PathValues.API2_V1_SCIM_SCHEMAS: Api2V1ScimSchemas,
        PathValues.API2_V1_SCIM_SERVICE_PROVIDER_CONFIG: Api2V1ScimServiceProviderConfig,
        PathValues.API2_V1_SCIM_SCHEMAS_SCHEMA_URN: Api2V1ScimSchemasSchemaUrn,
        PathValues.API2_V1_SCIM_USERS_USER_ID: Api2V1ScimUsersUserId,
        PathValues.API2_V1_SCIM_USERS: Api2V1ScimUsers,
        PathValues.API2_V1_SEGMENTATION_RULES_SEG_RULE_ID: Api2V1SegmentationRulesSegRuleId,
        PathValues.API2_V1_SEGMENTATION_RULES: Api2V1SegmentationRules,
        PathValues.API2_V1_SPELL_CHECK_CHECK: Api2V1SpellCheckCheck,
        PathValues.API2_V1_SPELL_CHECK_CHECK_JOB_UID: Api2V1SpellCheckCheckJobUid,
        PathValues.API2_V1_SPELL_CHECK_WORDS: Api2V1SpellCheckWords,
        PathValues.API2_V1_SPELL_CHECK_SUGGEST: Api2V1SpellCheckSuggest,
        PathValues.API2_V1_SUB_DOMAINS_SUB_DOMAIN_UID: Api2V1SubDomainsSubDomainUid,
        PathValues.API2_V1_SUB_DOMAINS: Api2V1SubDomains,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID: Api2V1TermBasesTermBaseUid,
        PathValues.API2_V1_TERM_BASES: Api2V1TermBases,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_UPLOAD: Api2V1TermBasesTermBaseUidUpload,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_CONCEPTS: Api2V1TermBasesTermBaseUidConcepts,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_CONCEPTS_CONCEPT_UID: Api2V1TermBasesTermBaseUidConceptsConceptUid,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_TERMS: Api2V1TermBasesTermBaseUidTerms,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_TERMS_TERM_ID: Api2V1TermBasesTermBaseUidTermsTermId,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_CONCEPTS_CONCEPT_ID: Api2V1TermBasesTermBaseUidConceptsConceptId,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_CONCEPTS_CONCEPT_ID_TERMS: Api2V1TermBasesTermBaseUidConceptsConceptIdTerms,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_LAST_BACKGROUND_TASK: Api2V1TermBasesTermBaseUidLastBackgroundTask,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_BROWSE: Api2V1TermBasesTermBaseUidBrowse,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_SEARCH: Api2V1TermBasesTermBaseUidSearch,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_EXPORT: Api2V1TermBasesTermBaseUidExport,
        PathValues.API2_V1_TERM_BASES_TERM_BASE_UID_METADATA: Api2V1TermBasesTermBaseUidMetadata,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_SEARCH: Api2V1TransMemoriesTransMemoryUidSearch,
        PathValues.API2_V1_TRANS_MEMORIES: Api2V1TransMemories,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID: Api2V1TransMemoriesTransMemoryUid,
        PathValues.API2_V1_TRANS_MEMORIES_EXTRACT_CLEANED: Api2V1TransMemoriesExtractCleaned,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_TARGET_LANGUAGES: Api2V1TransMemoriesTransMemoryUidTargetLanguages,
        PathValues.API2_V1_TRANS_MEMORIES_DOWNLOAD_CLEANED_ASYNC_REQUEST_ID: Api2V1TransMemoriesDownloadCleanedAsyncRequestId,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_SEGMENTS: Api2V1TransMemoriesTransMemoryUidSegments,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_RELATED_PROJECTS: Api2V1TransMemoriesTransMemoryUidRelatedProjects,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_METADATA: Api2V1TransMemoriesTransMemoryUidMetadata,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_SEGMENTS_SEGMENT_ID: Api2V1TransMemoriesTransMemoryUidSegmentsSegmentId,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_SEGMENTS_SEGMENT_ID_LANG_LANG: Api2V1TransMemoriesTransMemoryUidSegmentsSegmentIdLangLang,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_LAST_BACKGROUND_TASK: Api2V1TransMemoriesTransMemoryUidLastBackgroundTask,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_WILD_CARD_SEARCH: Api2V1TransMemoriesTransMemoryUidWildCardSearch,
        PathValues.API2_V1_TRANS_MEMORIES_DOWNLOAD_EXPORT_ASYNC_REQUEST_ID: Api2V1TransMemoriesDownloadExportAsyncRequestId,
        PathValues.API2_V1_TRANS_MEMORIES_TRANS_MEMORY_UID_EXPORT_BY_QUERY_ASYNC: Api2V1TransMemoriesTransMemoryUidExportByQueryAsync,
        PathValues.API2_V1_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TRANSLATIONS_TRANSLATE_WITH_MACHINE_TRANSLATION: Api2V1ProjectsProjectUidJobsJobUidTranslationsTranslateWithMachineTranslation,
        PathValues.API2_V1_PRICE_LISTS_PRICE_LIST_UID: Api2V1PriceListsPriceListUid,
        PathValues.API2_V1_PRICE_LISTS: Api2V1PriceLists,
        PathValues.API2_V1_PRICE_LISTS_PRICE_LIST_UID_PRICE_SETS: Api2V1PriceListsPriceListUidPriceSets,
        PathValues.API2_V1_PRICE_LISTS_PRICE_LIST_UID_PRICE_SETS_SOURCE_LANGUAGE_TARGET_LANGUAGE: Api2V1PriceListsPriceListUidPriceSetsSourceLanguageTargetLanguage,
        PathValues.API2_V1_PRICE_LISTS_PRICE_LIST_UID_PRICE_SETS_MINIMUM_PRICES: Api2V1PriceListsPriceListUidPriceSetsMinimumPrices,
        PathValues.API2_V1_PRICE_LISTS_PRICE_LIST_UID_PRICE_SETS_PRICES: Api2V1PriceListsPriceListUidPriceSetsPrices,
        PathValues.API2_V1_USERS_USER_UID: Api2V1UsersUserUid,
        PathValues.API2_V1_USERS_USER_UID_PROJECTS: Api2V1UsersUserUidProjects,
        PathValues.API2_V1_USERS_LAST_LOGINS: Api2V1UsersLastLogins,
        PathValues.API2_V1_USERS_USER_UID_JOBS: Api2V1UsersUserUidJobs,
        PathValues.API2_V1_USERS: Api2V1Users,
        PathValues.API2_V1_USERS_USER_UID_UPDATE_PASSWORD: Api2V1UsersUserUidUpdatePassword,
        PathValues.API2_V1_USERS_USER_UID_EMAIL_LOGIN_INFORMATION: Api2V1UsersUserUidEmailLoginInformation,
        PathValues.API2_V1_USERS_USER_UID_UNDELETE: Api2V1UsersUserUidUndelete,
        PathValues.API2_V1_USERS_USER_UID_LOGIN_STATISTICS: Api2V1UsersUserUidLoginStatistics,
        PathValues.API2_V1_USERS_USER_UID_WORKFLOW_STEPS: Api2V1UsersUserUidWorkflowSteps,
        PathValues.API2_V1_USERS_USER_UID_TARGET_LANGS: Api2V1UsersUserUidTargetLangs,
        PathValues.API2_V1_VENDORS_VENDOR_UID: Api2V1VendorsVendorUid,
        PathValues.API2_V1_VENDORS: Api2V1Vendors,
        PathValues.API2_V1_WEBHOOKS_CALLS_REPLAY_LATEST: Api2V1WebhooksCallsReplayLatest,
        PathValues.API2_V1_WEBHOOKS_CALLS: Api2V1WebhooksCalls,
        PathValues.API2_V1_WEBHOOKS_CALLS_REPLAY: Api2V1WebhooksCallsReplay,
        PathValues.API2_V1_WORKFLOW_STEPS: Api2V1WorkflowSteps,
        PathValues.API2_V1_WORKFLOW_STEPS_WORKFLOW_STEP_UID: Api2V1WorkflowStepsWorkflowStepUid,
        PathValues.API2_V2_ANALYSES_ANALYSE_UID: Api2V2AnalysesAnalyseUid,
        PathValues.API2_V2_ANALYSES: Api2V2Analyses,
        PathValues.API2_V2_ANALYSES_BULK: Api2V2AnalysesBulk,
        PathValues.API2_V2_CONNECTORS_CONNECTOR_ID_FOLDERS_FOLDER_FILES_FILE: Api2V2ConnectorsConnectorIdFoldersFolderFilesFile,
        PathValues.API2_V2_CONNECTORS_CONNECTOR_ID_FOLDERS_FOLDER_FILES_FILE_NAME_UPLOAD: Api2V2ConnectorsConnectorIdFoldersFolderFilesFileNameUpload,
        PathValues.API2_V2_CONNECTORS_CONNECTOR_ID_FOLDERS_FOLDER_FILES_FILE_TASKS_TASK_ID: Api2V2ConnectorsConnectorIdFoldersFolderFilesFileTasksTaskId,
        PathValues.API2_V2_JOBS_WORKFLOW_CHANGES: Api2V2JobsWorkflowChanges,
        PathValues.API2_V2_JOBS_JOB_UID_CONVERSATIONS_LQAS: Api2V2JobsJobUidConversationsLqas,
        PathValues.API2_V2_JOBS_JOB_UID_CONVERSATIONS_LQAS_CONVERSATION_ID: Api2V2JobsJobUidConversationsLqasConversationId,
        PathValues.API2_V2_JOBS_JOB_UID_CONVERSATIONS_LQAS_CONVERSATION_ID_COMMENTS: Api2V2JobsJobUidConversationsLqasConversationIdComments,
        PathValues.API2_V2_JOBS_JOB_UID_CONVERSATIONS_LQAS_CONVERSATION_ID_COMMENTS_COMMENT_ID: Api2V2JobsJobUidConversationsLqasConversationIdCommentsCommentId,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_PROVIDERS_SUGGEST: Api2V2ProjectsProjectUidProvidersSuggest,
        PathValues.API2_V2_PROJECTS_APPLY_TEMPLATE_ASYNC_TEMPLATE_UID: Api2V2ProjectsApplyTemplateAsyncTemplateUid,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_ACCESS_SETTINGS: Api2V2ProjectsProjectUidAccessSettings,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_WORKFLOW_STEPS: Api2V2ProjectsProjectUidWorkflowSteps,
        PathValues.API2_V2_PROJECTS_PROJECT_UID: Api2V2ProjectsProjectUid,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_QA_SETTINGS: Api2V2ProjectsProjectUidQaSettings,
        PathValues.API2_V2_PROJECTS_APPLY_TEMPLATE_TEMPLATE_UID: Api2V2ProjectsApplyTemplateTemplateUid,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS: Api2V2ProjectsProjectUidJobs,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_JOB_UID_QUALITY_ASSURANCES_SETTINGS: Api2V2ProjectsProjectUidJobsJobUidQualityAssurancesSettings,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_QUALITY_ASSURANCES_SETTINGS: Api2V2ProjectsProjectUidJobsQualityAssurancesSettings,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_WEB_EDITOR: Api2V2ProjectsProjectUidJobsWebEditor,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_PSEUDO_TRANSLATE: Api2V2ProjectsProjectUidJobsPseudoTranslate,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_PRE_TRANSLATE: Api2V2ProjectsProjectUidJobsPreTranslate,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_TRANSLATIONS: Api2V2ProjectsProjectUidJobsTranslations,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_JOB_UID_PROVIDERS_SUGGEST: Api2V2ProjectsProjectUidJobsJobUidProvidersSuggest,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TARGET_FILE: Api2V2ProjectsProjectUidJobsJobUidTargetFile,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_JOB_UID_DOWNLOAD_TARGET_FILE_ASYNC_REQUEST_ID: Api2V2ProjectsProjectUidJobsJobUidDownloadTargetFileAsyncRequestId,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_QUALITY_ASSURANCES_IGNORED_WARNINGS: Api2V2ProjectsProjectUidJobsQualityAssurancesIgnoredWarnings,
        PathValues.API2_V2_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_TRANS_MEMORIES: Api2V2ProjectTemplatesProjectTemplateUidTransMemories,
        PathValues.API2_V2_QUOTES: Api2V2Quotes,
        PathValues.API2_V2_TRANS_MEMORIES_TRANS_MEMORY_UID_EXPORT: Api2V2TransMemoriesTransMemoryUidExport,
        PathValues.API2_V2_TRANS_MEMORIES_TRANS_MEMORY_UID_SEGMENTS: Api2V2TransMemoriesTransMemoryUidSegments,
        PathValues.API2_V2_TRANS_MEMORIES_TRANS_MEMORY_UID_IMPORT: Api2V2TransMemoriesTransMemoryUidImport,
        PathValues.API2_V2_WEBHOOKS_WEB_HOOK_UID: Api2V2WebhooksWebHookUid,
        PathValues.API2_V2_WEBHOOKS: Api2V2Webhooks,
        PathValues.API2_V2_WEBHOOKS_PREVIEWS: Api2V2WebhooksPreviews,
        PathValues.API2_V2_WEBHOOKS_WEBHOOK_UID_TEST: Api2V2WebhooksWebhookUidTest,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TERM_BASES_SEARCH_BY_JOB: Api2V2ProjectsProjectUidJobsJobUidTermBasesSearchByJob,
        PathValues.API2_V2_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TERM_BASES_SEARCH_IN_TEXT_BY_JOB: Api2V2ProjectsProjectUidJobsJobUidTermBasesSearchInTextByJob,
        PathValues.API2_V3_ANALYSES_ANALYSE_UID: Api2V3AnalysesAnalyseUid,
        PathValues.API2_V3_AUTH_LOGIN: Api2V3AuthLogin,
        PathValues.API2_V3_AUTH_LOGIN_TO_SESSION: Api2V3AuthLoginToSession,
        PathValues.API2_V3_AUTH_LOGIN_OTHER: Api2V3AuthLoginOther,
        PathValues.API2_V3_JOBS: Api2V3Jobs,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TRANS_MEMORIES_SEARCH: Api2V3ProjectsProjectUidJobsJobUidTransMemoriesSearch,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_JOB_UID_TRANS_MEMORIES_WILD_CARD_SEARCH: Api2V3ProjectsProjectUidJobsJobUidTransMemoriesWildCardSearch,
        PathValues.API2_V3_JOBS_JOB_UID_CONVERSATIONS_PLAINS_CONVERSATION_ID_COMMENTS: Api2V3JobsJobUidConversationsPlainsConversationIdComments,
        PathValues.API2_V3_JOBS_JOB_UID_CONVERSATIONS_PLAINS: Api2V3JobsJobUidConversationsPlains,
        PathValues.API2_V3_JOBS_JOB_UID_CONVERSATIONS_PLAINS_CONVERSATION_ID_COMMENTS_COMMENT_ID: Api2V3JobsJobUidConversationsPlainsConversationIdCommentsCommentId,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_PRE_TRANSLATE_SETTINGS: Api2V3ProjectsProjectUidPreTranslateSettings,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_ANALYSES: Api2V3ProjectsProjectUidAnalyses,
        PathValues.API2_V3_PROJECTS: Api2V3Projects,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_EXPORT: Api2V3ProjectsProjectUidJobsExport,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_JOB_UID_QUALITY_ASSURANCES_RUN: Api2V3ProjectsProjectUidJobsJobUidQualityAssurancesRun,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_QUALITY_ASSURANCES_RUN: Api2V3ProjectsProjectUidJobsQualityAssurancesRun,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_QUALITY_ASSURANCES_SEGMENTS_RUN: Api2V3ProjectsProjectUidJobsQualityAssurancesSegmentsRun,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_JOBS_JOB_UID_ANALYSES: Api2V3ProjectsProjectUidJobsJobUidAnalyses,
        PathValues.API2_V3_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_PRE_TRANSLATE_SETTINGS: Api2V3ProjectTemplatesProjectTemplateUidPreTranslateSettings,
        PathValues.API2_V3_PROJECT_TEMPLATES_PROJECT_TEMPLATE_UID_TRANS_MEMORIES: Api2V3ProjectTemplatesProjectTemplateUidTransMemories,
        PathValues.API2_V3_PROJECTS_PROJECT_UID_TRANS_MEMORIES: Api2V3ProjectsProjectUidTransMemories,
        PathValues.API2_V3_USERS_USER_UID: Api2V3UsersUserUid,
        PathValues.API2_V3_USERS: Api2V3Users,
        PathValues.API2_V3_USERS_USER_UID_DISABLE_TWO_FACTOR_AUTH: Api2V3UsersUserUidDisableTwoFactorAuth,
    }
)
