from phrasetms_client.paths.api2_v1_project_templates_project_template_uid_custom_fields_field_instance_uid.get import ApiForget
from phrasetms_client.paths.api2_v1_project_templates_project_template_uid_custom_fields_field_instance_uid.put import ApiForput
from phrasetms_client.paths.api2_v1_project_templates_project_template_uid_custom_fields_field_instance_uid.delete import ApiFordelete


class Api2V1ProjectTemplatesProjectTemplateUidCustomFieldsFieldInstanceUid(
    ApiForget,
    ApiForput,
    ApiFordelete,
):
    pass
