# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import openapi_client
from openapi_client.paths.api2_v2_projects_project_uid_jobs_quality_assurances_ignored_warnings import delete  # noqa: E501
from openapi_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApi2V2ProjectsProjectUidJobsQualityAssurancesIgnoredWarnings(ApiTestMixin, unittest.TestCase):
    """
    Api2V2ProjectsProjectUidJobsQualityAssurancesIgnoredWarnings unit test stubs
        Delete ignored warnings  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = delete.ApiFordelete(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 204


if __name__ == '__main__':
    unittest.main()
