# coding: utf-8

"""
    Phrase TMS API

    Welcome to Phrase's TMS API documentation.    Please visit our [help center](https://support.phrase.com/hc/en-us/sections/5709662083612) for more information about the APIs.    If you have any questions, please contact [Support](https://support.phrase.com/hc/requests/new).    Please, include the `User-Agent` header with the name of your application or project. It might be a good idea to include some sort of contact information as well, so that we can get in touch if necessary. Examples of excellent `User-Agent` headers:  > User-Agent: Example mobile app (example@phrase.com) <br/> User-Agent: ACME Inc Java 1.8 Client (http://acmeinc.com/contact)  # noqa: E501

    The version of the OpenAPI document: Latest
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class SearchTMResponseDto(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            segmentId = schemas.StrSchema
        
            @staticmethod
            def source() -> typing.Type['SearchTMSegmentDto']:
                return SearchTMSegmentDto
            
            
            class translations(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['SearchTMSegmentDto']:
                        return SearchTMSegmentDto
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['SearchTMSegmentDto'], typing.List['SearchTMSegmentDto']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'translations':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'SearchTMSegmentDto':
                    return super().__getitem__(i)
        
            @staticmethod
            def transMemory() -> typing.Type['SearchTMTransMemoryDto']:
                return SearchTMTransMemoryDto
            grossScore = schemas.Float64Schema
            score = schemas.Float64Schema
            subSegment = schemas.BoolSchema
            __annotations__ = {
                "segmentId": segmentId,
                "source": source,
                "translations": translations,
                "transMemory": transMemory,
                "grossScore": grossScore,
                "score": score,
                "subSegment": subSegment,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["segmentId"]) -> MetaOapg.properties.segmentId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["source"]) -> 'SearchTMSegmentDto': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["translations"]) -> MetaOapg.properties.translations: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transMemory"]) -> 'SearchTMTransMemoryDto': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["grossScore"]) -> MetaOapg.properties.grossScore: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["score"]) -> MetaOapg.properties.score: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subSegment"]) -> MetaOapg.properties.subSegment: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["segmentId", "source", "translations", "transMemory", "grossScore", "score", "subSegment", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["segmentId"]) -> typing.Union[MetaOapg.properties.segmentId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["source"]) -> typing.Union['SearchTMSegmentDto', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["translations"]) -> typing.Union[MetaOapg.properties.translations, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transMemory"]) -> typing.Union['SearchTMTransMemoryDto', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["grossScore"]) -> typing.Union[MetaOapg.properties.grossScore, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["score"]) -> typing.Union[MetaOapg.properties.score, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subSegment"]) -> typing.Union[MetaOapg.properties.subSegment, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["segmentId", "source", "translations", "transMemory", "grossScore", "score", "subSegment", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        segmentId: typing.Union[MetaOapg.properties.segmentId, str, schemas.Unset] = schemas.unset,
        source: typing.Union['SearchTMSegmentDto', schemas.Unset] = schemas.unset,
        translations: typing.Union[MetaOapg.properties.translations, list, tuple, schemas.Unset] = schemas.unset,
        transMemory: typing.Union['SearchTMTransMemoryDto', schemas.Unset] = schemas.unset,
        grossScore: typing.Union[MetaOapg.properties.grossScore, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        score: typing.Union[MetaOapg.properties.score, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        subSegment: typing.Union[MetaOapg.properties.subSegment, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SearchTMResponseDto':
        return super().__new__(
            cls,
            *_args,
            segmentId=segmentId,
            source=source,
            translations=translations,
            transMemory=transMemory,
            grossScore=grossScore,
            score=score,
            subSegment=subSegment,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.search_tm_segment_dto import SearchTMSegmentDto
from openapi_client.model.search_tm_trans_memory_dto import SearchTMTransMemoryDto
