# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from openapi_client.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    ADDITIONAL_WORKFLOW_STEP = "Additional Workflow Step"
    ANALYSIS = "Analysis"
    ASYNC_REQUEST = "Async Request"
    AUTHENTICATION = "Authentication"
    BILINGUAL_FILE = "Bilingual File"
    BUSINESS_UNIT = "Business Unit"
    CLIENT = "Client"
    CONNECTOR = "Connector"
    CONVERSATIONS = "Conversations"
    COST_CENTER = "Cost Center"
    CUSTOM_FIELDS = "Custom Fields"
    CUSTOM_FILE_TYPE = "Custom File Type"
    DOMAIN = "Domain"
    EMAIL_TEMPLATE = "Email Template"
    FILE = "File"
    GLOSSARY = "Glossary"
    IMPORT_SETTINGS = "Import settings"
    JOB = "Job"
    LANGUAGE_QUALITY_ASSESSMENT = "Language Quality Assessment"
    MACHINE_TRANSLATION = "Machine Translation"
    MACHINE_TRANSLATION_SETTINGS = "Machine Translation Settings"
    MAPPING = "Mapping"
    NET_RATE_SCHEME = "Net Rate Scheme"
    PRICE_LIST = "Price List"
    PROJECT = "Project"
    PROJECT_REFERENCE_FILE = "Project Reference File"
    PROJECT_TEMPLATE = "Project Template"
    PROVIDER = "Provider"
    QUALITY_ASSURANCE = "Quality Assurance"
    QUOTE = "Quote"
    SCIM = "SCIM"
    SEGMENT = "Segment"
    SEGMENTATION_RULES = "Segmentation Rules"
    SPELL_CHECK = "Spell Check"
    SUB_DOMAIN = "SubDomain"
    SUPPORTED_LANGUAGES = "Supported Languages"
    TERM_BASE = "Term Base"
    TRANSLATION = "Translation"
    TRANSLATION_MEMORY = "Translation Memory"
    USER = "User"
    VENDOR = "Vendor"
    WEBHOOK = "Webhook"
    WORKFLOW_STEP = "Workflow Step"
    WORKFLOW_CHANGES = "Workflow changes"
