# coding: utf-8

"""
    Phrase TMS API

    Welcome to Phrase's TMS API documentation.    Please visit our [help center](https://support.phrase.com/hc/en-us/sections/5709662083612) for more information about the APIs.    If you have any questions, please contact [Support](https://support.phrase.com/hc/requests/new).    Please, include the `User-Agent` header with the name of your application or project. It might be a good idea to include some sort of contact information as well, so that we can get in touch if necessary. Examples of excellent `User-Agent` headers:  > User-Agent: Example mobile app (example@phrase.com) <br/> User-Agent: ACME Inc Java 1.8 Client (http://acmeinc.com/contact)  # noqa: E501

    The version of the OpenAPI document: Latest
    Generated by: https://openapi-generator.tech
"""

from phrasetms_client.paths.api2_v1_scim_users.post import CreateUserScim
from phrasetms_client.paths.api2_v1_scim_users_user_id.delete import DeleteUser
from phrasetms_client.paths.api2_v1_scim_users_user_id.put import EditUser
from phrasetms_client.paths.api2_v1_scim_resource_types.get import GetResourceTypes
from phrasetms_client.paths.api2_v1_scim_schemas_schema_urn.get import GetSchemaByUrn
from phrasetms_client.paths.api2_v1_scim_schemas.get import GetSchemas
from phrasetms_client.paths.api2_v1_scim_users_user_id.get import GetScimUser
from phrasetms_client.paths.api2_v1_scim_service_provider_config.get import GetServiceProviderConfigDto
from phrasetms_client.paths.api2_v1_scim_users_user_id.patch import PatchUser
from phrasetms_client.paths.api2_v1_scim_users.get import SearchUsers


class SCIMApi(
    CreateUserScim,
    DeleteUser,
    EditUser,
    GetResourceTypes,
    GetSchemaByUrn,
    GetSchemas,
    GetScimUser,
    GetServiceProviderConfigDto,
    PatchUser,
    SearchUsers,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
