# coding: utf-8

"""
    Phrase TMS API

    Welcome to Phrase's TMS API documentation.    Please visit our [help center](https://support.phrase.com/hc/en-us/sections/5709662083612) for more information about the APIs.    If you have any questions, please contact [Support](https://support.phrase.com/hc/requests/new).    Please, include the `User-Agent` header with the name of your application or project. It might be a good idea to include some sort of contact information as well, so that we can get in touch if necessary. Examples of excellent `User-Agent` headers:  > User-Agent: Example mobile app (example@phrase.com) <br/> User-Agent: ACME Inc Java 1.8 Client (http://acmeinc.com/contact)  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EditAnalyseV2Dto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'provider': 'ProviderReference',
        'net_rate_scheme': 'UidReference'
    }

    attribute_map = {
        'name': 'name',
        'provider': 'provider',
        'net_rate_scheme': 'netRateScheme'
    }

    def __init__(self, name=None, provider=None, net_rate_scheme=None):  # noqa: E501
        """EditAnalyseV2Dto - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._provider = None
        self._net_rate_scheme = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if provider is not None:
            self.provider = provider
        if net_rate_scheme is not None:
            self.net_rate_scheme = net_rate_scheme

    @property
    def name(self):
        """Gets the name of this EditAnalyseV2Dto.  # noqa: E501


        :return: The name of this EditAnalyseV2Dto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EditAnalyseV2Dto.


        :param name: The name of this EditAnalyseV2Dto.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def provider(self):
        """Gets the provider of this EditAnalyseV2Dto.  # noqa: E501


        :return: The provider of this EditAnalyseV2Dto.  # noqa: E501
        :rtype: ProviderReference
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this EditAnalyseV2Dto.


        :param provider: The provider of this EditAnalyseV2Dto.  # noqa: E501
        :type: ProviderReference
        """

        self._provider = provider

    @property
    def net_rate_scheme(self):
        """Gets the net_rate_scheme of this EditAnalyseV2Dto.  # noqa: E501


        :return: The net_rate_scheme of this EditAnalyseV2Dto.  # noqa: E501
        :rtype: UidReference
        """
        return self._net_rate_scheme

    @net_rate_scheme.setter
    def net_rate_scheme(self, net_rate_scheme):
        """Sets the net_rate_scheme of this EditAnalyseV2Dto.


        :param net_rate_scheme: The net_rate_scheme of this EditAnalyseV2Dto.  # noqa: E501
        :type: UidReference
        """

        self._net_rate_scheme = net_rate_scheme

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EditAnalyseV2Dto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EditAnalyseV2Dto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
