# coding: utf-8

"""
    Phrase TMS API

    Welcome to Phrase's TMS API documentation.    Please visit our [help center](https://support.phrase.com/hc/en-us/sections/5709662083612) for more information about the APIs.    If you have any questions, please contact [Support](https://support.phrase.com/hc/requests/new).    Please, include the `User-Agent` header with the name of your application or project. It might be a good idea to include some sort of contact information as well, so that we can get in touch if necessary. Examples of excellent `User-Agent` headers:  > User-Agent: Example mobile app (example@phrase.com) <br/> User-Agent: ACME Inc Java 1.8 Client (http://acmeinc.com/contact)  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from phrasetms_client.models import FileImportSettingsCreateDto


class ImportSettingsCreateDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "name": "str",
        "file_import_settings": "FileImportSettingsCreateDto",
    }

    attribute_map = {"name": "name", "file_import_settings": "fileImportSettings"}

    def __init__(self, name=None, file_import_settings=None):  # noqa: E501
        """ImportSettingsCreateDto - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._file_import_settings = None
        self.discriminator = None
        self.name = name
        self.file_import_settings = file_import_settings

    @property
    def name(self) -> str:
        """Gets the name of this ImportSettingsCreateDto.  # noqa: E501


        :return: The name of this ImportSettingsCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ImportSettingsCreateDto.


        :param name: The name of this ImportSettingsCreateDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501

        self._name = name

    @property
    def file_import_settings(self) -> FileImportSettingsCreateDto:
        """Gets the file_import_settings of this ImportSettingsCreateDto.  # noqa: E501


        :return: The file_import_settings of this ImportSettingsCreateDto.  # noqa: E501
        :rtype: FileImportSettingsCreateDto
        """
        return self._file_import_settings

    @file_import_settings.setter
    def file_import_settings(self, file_import_settings):
        """Sets the file_import_settings of this ImportSettingsCreateDto.


        :param file_import_settings: The file_import_settings of this ImportSettingsCreateDto.  # noqa: E501
        :type: FileImportSettingsCreateDto
        """
        if file_import_settings is None:
            raise ValueError(
                "Invalid value for `file_import_settings`, must not be `None`"
            )  # noqa: E501

        self._file_import_settings = file_import_settings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ImportSettingsCreateDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImportSettingsCreateDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
