# coding: utf-8

"""
    Phrase TMS API

    Welcome to Phrase's TMS API documentation.    Please visit our [help center](https://support.phrase.com/hc/en-us/sections/5709662083612) for more information about the APIs.    If you have any questions, please contact [Support](https://support.phrase.com/hc/requests/new).    Please, include the `User-Agent` header with the name of your application or project. It might be a good idea to include some sort of contact information as well, so that we can get in touch if necessary. Examples of excellent `User-Agent` headers:  > User-Agent: Example mobile app (example@phrase.com) <br/> User-Agent: ACME Inc Java 1.8 Client (http://acmeinc.com/contact)  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SetTermBaseDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'read_term_bases': 'list[IdReference]',
        'write_term_base': 'IdReference',
        'quality_assurance_term_bases': 'list[IdReference]',
        'target_lang': 'str'
    }

    attribute_map = {
        'read_term_bases': 'readTermBases',
        'write_term_base': 'writeTermBase',
        'quality_assurance_term_bases': 'qualityAssuranceTermBases',
        'target_lang': 'targetLang'
    }

    def __init__(self, read_term_bases=None, write_term_base=None, quality_assurance_term_bases=None, target_lang=None):  # noqa: E501
        """SetTermBaseDto - a model defined in Swagger"""  # noqa: E501
        self._read_term_bases = None
        self._write_term_base = None
        self._quality_assurance_term_bases = None
        self._target_lang = None
        self.discriminator = None
        if read_term_bases is not None:
            self.read_term_bases = read_term_bases
        if write_term_base is not None:
            self.write_term_base = write_term_base
        if quality_assurance_term_bases is not None:
            self.quality_assurance_term_bases = quality_assurance_term_bases
        if target_lang is not None:
            self.target_lang = target_lang

    @property
    def read_term_bases(self):
        """Gets the read_term_bases of this SetTermBaseDto.  # noqa: E501


        :return: The read_term_bases of this SetTermBaseDto.  # noqa: E501
        :rtype: list[IdReference]
        """
        return self._read_term_bases

    @read_term_bases.setter
    def read_term_bases(self, read_term_bases):
        """Sets the read_term_bases of this SetTermBaseDto.


        :param read_term_bases: The read_term_bases of this SetTermBaseDto.  # noqa: E501
        :type: list[IdReference]
        """

        self._read_term_bases = read_term_bases

    @property
    def write_term_base(self):
        """Gets the write_term_base of this SetTermBaseDto.  # noqa: E501


        :return: The write_term_base of this SetTermBaseDto.  # noqa: E501
        :rtype: IdReference
        """
        return self._write_term_base

    @write_term_base.setter
    def write_term_base(self, write_term_base):
        """Sets the write_term_base of this SetTermBaseDto.


        :param write_term_base: The write_term_base of this SetTermBaseDto.  # noqa: E501
        :type: IdReference
        """

        self._write_term_base = write_term_base

    @property
    def quality_assurance_term_bases(self):
        """Gets the quality_assurance_term_bases of this SetTermBaseDto.  # noqa: E501


        :return: The quality_assurance_term_bases of this SetTermBaseDto.  # noqa: E501
        :rtype: list[IdReference]
        """
        return self._quality_assurance_term_bases

    @quality_assurance_term_bases.setter
    def quality_assurance_term_bases(self, quality_assurance_term_bases):
        """Sets the quality_assurance_term_bases of this SetTermBaseDto.


        :param quality_assurance_term_bases: The quality_assurance_term_bases of this SetTermBaseDto.  # noqa: E501
        :type: list[IdReference]
        """

        self._quality_assurance_term_bases = quality_assurance_term_bases

    @property
    def target_lang(self):
        """Gets the target_lang of this SetTermBaseDto.  # noqa: E501


        :return: The target_lang of this SetTermBaseDto.  # noqa: E501
        :rtype: str
        """
        return self._target_lang

    @target_lang.setter
    def target_lang(self, target_lang):
        """Sets the target_lang of this SetTermBaseDto.


        :param target_lang: The target_lang of this SetTermBaseDto.  # noqa: E501
        :type: str
        """

        self._target_lang = target_lang

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SetTermBaseDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SetTermBaseDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
