# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'pipenv'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        sudo pip install pipenv
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt-get update
        pipenv install
    - name: Build package
      run: make build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
